### ISSUE TITLE
Consider using shadow DOM instead of an iframe

### ISSUE THREAD

**Issue by AminZibayi** [ZachSaucier/Just-Read#282] opened 2019-12-02 15:45 UTC
**Describe the bug**
Those extensions that will show popups based on the selected text (e.g. Google Translate) won't work

**To Reproduce**
1. Install Google Translate extension
2. Click on JP
3. Select a word
4. You won't see any icons or popups beside the selected text

**Expected behavior**
You should see a popup or an icon beside the selected text

**Please complete the following information:**
 - OS: Windows 10
 - Browser Brave(chrome)
 - Version 1.0.1 (chromuim: 78)

**Additional context**
It may happen because JP renders content in an iframe in this situation using shadow DOM would solve the problem and also please note that the `z-index` of container `iframe` is very high (only decreasing z-index didn't fix the issue)
I copied the innerHTML of the `iframe` and pasted it in a `.html` file after opening that file and selecting some text the popups displayed normally.

**Comment by ZachSaucier** [comment] 2019-12-02 15:49
This is technically a duplicate of #29 but I haven't thought about using the shadow DOM to prevent styles from being inherited. 

I'll change this from a bug to a feature request and leave it open while I investigate the feasibility of such an approach. 

z-index is necessarily high to work properly on some sites. It's unrelated to this issue.

**Comment by AminZibayi** [comment] 2019-12-02 15:53
Thanks for your very quick response I wish i get some free time to work on this feature

**Comment by ZachSaucier** [comment] 2019-12-04 03:52
FYI I started work on this. It's a major reworking for how Just Read functions so don't expect it to be a quick process. It may not even work in the end, we'll see.

**Comment by ZachSaucier** [comment] 2020-01-11 23:56
Found some time to work on this. No hitch so far, the free version of Just Read is converted now - I will just have to do a bit of testing. 

I'll release after I convert and test the premium version as well. Still no projected date because it depends when I can find the time.

**Comment by ZachSaucier** [comment] 2020-01-25 22:39
After spending hours on attempting this, I don't think it's possible for Just Read Premium. For Premium, I use a highlighter functionality that's a part of a library called [Rangy](https://github.com/timdown/rangy/wiki/Highlighter-Module). Unfortunately I don't think any of the library but especially the highlighter module is setup to support shadow DOM content. `rangy.createHighlighter(shadowRoot)` doesn't help. Neither does manually setting the `selection` of rangy's options to `rangyOptions.selection = shadowRoot.getSelection()`. So unless [the fork of Rangy](https://github.com/pburrows/rangy-updated) that hasn't been touched in over a year gets support for shadow DOM content, this is unlikely to happen. 

Theoretically I could recreate related functionality of Rangy using my own scripts but that is too much work for the amount of time that I have right now. It would need to support not only adding <span>s to the selected content, but also add IDs, callbacks for creation and deletion, particular class names depending on which type of highlight a user wants, support for mixing highlights (i.e. something like `some text <span class="highlight-yellow">some more text</span> continued highlighting` being turned into `some text <span class="highlight-yellow">some more <span class="text-color-black">text</span></span><span class="text-color-black"> continued highlighting</span>`), and properly removing previous highlights all with shadow DOM content. 

I will not move _only_ the free version to using the shadow DOM because then I'd have to maintain two version and people moving from the free version to the premium version would potentially faces differences in how Just Read performs, which is suboptimal. 

I will keep my work on a branch of Just Read to potentially do at a later point, but I doubt that will happen.

**Closed by ZachSaucier** 2020-01-25 22:39 UTC
Labels: enhancement
