### ISSUE TITLE
Comment being auto-selected, so no content is shown

### ISSUE THREAD

**Issue by davay** [ZachSaucier/Just-Read#54] opened 2017-03-01 08:10 UTC
Only the headline was detected.

I was trying to read this article specifically: 
http://www.oregonlive.com/washingtoncounty/index.ssf/2010/04/test_sample_shows_racial_bias.html

screenshot: 
![screenshot_20170301_000946](https://cloud.githubusercontent.com/assets/20072630/23451141/8246013c-fe13-11e6-835c-caa39238f197.png)

Thank you

**Comment by ZachSaucier** [comment] 2017-03-01 12:26
Thanks for the report! 

What's happening here is that the auto-selection is selecting part of the comments section, but then Just Read is showing anything because it (attempts to) hide comments and such. You can manually select the content via [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) and it should work great.

I will look into the auto-selection to see if I can better handle cases like this when I get some free time.

**Comment by ZachSaucier** [comment] 2017-08-08 02:49
Very interestingly, this site fails to load on the first run using version 1.1.0, but the second time works. I'll continue to look into it.

**Comment by ZachSaucier** [comment] 2017-11-06 02:33
I'm closing this as a duplicate of an earlier issue because the core problem is the same.

**Closed by ZachSaucier** 2017-11-06 02:33 UTC
Labels: duplicate
