### ISSUE TITLE
Premium 3.3.7 "too many shared articles" error

### ISSUE THREAD

**Issue by gshinton1** [ZachSaucier/Just-Read#238] opened 2019-03-16 17:18 UTC
Just Read Premium 3.3.7 has been running fine for ~2 weeks but suddenly started misbehaving.
Looks like same issue as in #174 ,#176, and #199.
Using Windows 7, Chrome 72.0.3626.121.
Turning off all other extensions doesn't help.
Attaching PDF of results for URL <https://www.alternativenation.net/led-zeppelin-member-brutally-rejected-beatles-icon>. Seems to happen on all pages.
Clicking anywhere on JRP-rendered result yields page displayed in dark mode, although I've never selected dark mode in options.
[JustReadTest.pdf](https://github.com/ZachSaucier/Just-Read/files/2974125/JustReadTest.pdf)

**Comment by ZachSaucier** [comment] 2019-03-17 14:36
It sounds like you're describing two different errors that are happening:

- You can't share pages which is related to the stylesheet failing to load (resulting in the "JustReadTest.pdf" that you send)
- The dark stylesheet is being used over the default white one

These seem to be in conflict with each other... can you better describe how to reproduce these errors? 

Are there any error messages in the console when you try to run JR (press F12 to view the console)? How about when you try to share a page?

Right now I don't have a computer to test JR on Windows 7, so if it's an OS-related issue I'm not sure I'll be able to help until I can find a computer running Windows 7.

**Comment by gshinton1** [comment] 2019-03-17 17:33
Here's a bunch of console output to wade through. All other extensions are disabled for the following.

Using as a "normal" page <https://onezero.medium.com/how-to-quit-your-job-in-837-easy-steps-af2b121f757b> yields no errors or warnings when loading the page or clicking on the JRP icon. Only the following 3 "verbose" messages appear:
[Violation] 'setTimeout' handler took 234ms
[Violation] Forced reflow while executing JavaScript took 37ms
[Violation] Forced reflow while executing JavaScript took 69ms

Sharing and all other functions work normally. The only problem seems to be that it renders in dark mode -- as do all other "normal" pages -- which it didn't do before.

On the other hand, the "problem" page at <https://www.alternativenation.net/led-zeppelin-member-brutally-rejected-beatles-icon/> generates a myriad of messages.  First, when loading the page itself, there are 25 messages. 
----- 7 errors:
ffwd_frontend.js?ver=1.0.19:712 Uncaught TypeError: Cannot read property 'id' of undefined
    at do_something_with_data_blog_style (ffwd_frontend.js?ver=1.0.19:712)
    at ffwd_fill_likes_blog_style (ffwd_frontend.js?ver=1.0.19:672)
    at (index):2519
do_something_with_data_blog_style @ ffwd_frontend.js?ver=1.0.19:712
ffwd_fill_likes_blog_style @ ffwd_frontend.js?ver=1.0.19:672
(anonymous) @ (index):2519
jquery.js?ver=1.12.4:4 GET https://www.alternativenation.net/wp-admin/admin-ajax.php?action=ffwd_autoupdate 403
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
(anonymous) @ ffwd_frontend.js?ver=1.0.19:1070
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
jquery.js?ver=1.12.4:4 POST https://www.alternativenation.net/wp-admin/admin-ajax.php?td_theme_name=Newspaper&v=6.6.5 403
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
tdGetViewsCountsAjax @ tagdiv_theme.js?ver=6.6.5:5846
jQuery_ready @ (index):2774
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
(index):1 Refused to execute script from 'https://www.alternativenation.net/led-zeppelin-member-brutally-rejected-beatles-icon/?cf_action=sync_comments&post_id=119443' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
rudy.adsnative.com/cm.gif?dspid=2015930208&buid=0765efb2-1e56-4bc4-bd4e-076112f21e41:1 GET https://rudy.adsnative.com/cm.gif?dspid=2015930208&buid=0765efb2-1e56-4bc4-bd4e-076112f21e41 net::ERR_TOO_MANY_REDIRECTS
Image (async)
dropCookieMatchingPixel @ render.v2.js:2
(anonymous) @ render.v2.js:2
(anonymous) @ render.v2.js:2
cm.gif:1 Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
render.v2.js:2 GET https://rudy.adsnative.com/cm.gif?dspid=556869201&buid=88652f9f-7b76-4599-9dab-cf152bf2a08e net::ERR_TOO_MANY_REDIRECTS
dropCookieMatchingPixel @ render.v2.js:2
(anonymous) @ render.v2.js:2
(anonymous) @ render.v2.js:2
----- 6 warnings:
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://ads.yahoo.com/cms/v1?esig=2~5f154148a476e7968097159639c70f89b0335754&nwid=10000279210&sigv=1 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Image (async)
dropCookieMatchingPixel @ render.v2.js:2
(anonymous) @ render.v2.js:2
(anonymous) @ render.v2.js:2
The resource https://c.disquscdn.com/next/embed/styles/lounge.9974049bf7b0591e5d4f055cb67f3ee3.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://c.disquscdn.com/next/embed/common.bundle.880980e048a2432334f13013030456ac.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://disqus.com/next/config.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://c.disquscdn.com/next/embed/lounge.bundle.7ca5005d1897180d07d928e89d2628be.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
render.v2.js:2 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://ads.yahoo.com/cms/v1?esig=2~5f154148a476e7968097159639c70f89b0335754&nwid=10000279210&sigv=1 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
dropCookieMatchingPixel @ render.v2.js:2
(anonymous) @ render.v2.js:2
(anonymous) @ render.v2.js:2
----- 3 info:
JQMIGRATE: Migrate is installed, version 1.4.1
twitter_adapter.js:1 googletag is not on scope, creating a new one. . .
twitter_adapter.js:1 googletag is not on scope, creating a new one. . .
----- 9 verbose:
[Violation] Forced reflow while executing JavaScript took <N>ms
ads?client=ca-pub-5296172734705889&output=html&h=50&slotname=9645592189&adk=3985850539&adf=1996273275&w=320&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=320x50&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&wgl=1&dt=1552842680356&bpp=22&bdt=955&fdt=24&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=687865738&dssz=22&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=144&ady=10&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeE|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=3769963683&ifi=1&uci=1.fvqg64vvsvyt&fsb=1&xpc=UmRWdgiTKA&p=https%3A//www.alternativenation.net&dtd=54:208 [Violation] 'browserRender' handler took 210ms
85[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
ads?client=ca-pub-5296172734705889&output=html&h=250&slotname=7889657381&adk=462315722&adf=1975853983&w=300&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=300x250&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&avail_w=587&wgl=1&dt=1552842680954&bpp=26&bdt=1553&fdt=28&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0%2C320x50&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=44023407146&dssz=27&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=154&ady=1304&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeEbr|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=1335172480&ifi=2&uci=2.4wm2mz1acxkv&fsb=1&xpc=z98wHo8TzE&p=https%3A//www.alternativenation.net&dtd=39:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
F @ ads?client=ca-pub-5296172734705889&output=html&h=250&slotname=7889657381&adk=462315722&adf=1975853983&w=300&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=300x250&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&avail_w=587&wgl=1&dt=1552842680954&bpp=26&bdt=1553&fdt=28&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0%2C320x50&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=44023407146&dssz=27&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=154&ady=1304&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeEbr|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=1335172480&ifi=2&uci=2.4wm2mz1acxkv&fsb=1&xpc=z98wHo8TzE&p=https%3A//www.alternativenation.net&dtd=39:1
11[Violation] 'setTimeout' handler took <N>ms
ads?client=ca-pub-5296172734705889&output=html&h=250&slotname=7889657381&adk=462315722&adf=1975853983&w=300&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=300x250&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&avail_w=587&wgl=1&dt=1552842680954&bpp=26&bdt=1553&fdt=28&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0%2C320x50&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=44023407146&dssz=27&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=154&ady=1304&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeEbr|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=1335172480&ifi=2&uci=2.4wm2mz1acxkv&fsb=1&xpc=z98wHo8TzE&p=https%3A//www.alternativenation.net&dtd=39:1 [Violation] 'load' handler took 287ms
ads?client=ca-pub-5296172734705889&output=html&h=50&slotname=9645592189&adk=3985850539&adf=1996273275&w=320&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=320x50&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&wgl=1&dt=1552842680356&bpp=22&bdt=955&fdt=24&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=687865738&dssz=22&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=144&ady=10&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeE|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=3769963683&ifi=1&uci=1.fvqg64vvsvyt&fsb=1&xpc=UmRWdgiTKA&p=https%3A//www.alternativenation.net&dtd=54:221 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
F @ ads?client=ca-pub-5296172734705889&output=html&h=50&slotname=9645592189&adk=3985850539&adf=1996273275&w=320&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=320x50&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&wgl=1&dt=1552842680356&bpp=22&bdt=955&fdt=24&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=687865738&dssz=22&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=144&ady=10&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeE|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=3769963683&ifi=1&uci=1.fvqg64vvsvyt&fsb=1&xpc=UmRWdgiTKA&p=https%3A//www.alternativenation.net&dtd=54:221
VM838 widgets.js:8 [Violation] 'requestAnimationFrame' handler took 62ms
ads?client=ca-pub-5296172734705889&output=html&h=50&slotname=9645592189&adk=3985850539&adf=1996273275&w=320&lmt=1552842680&guci=2.2.0.0.2.2.0.0&format=320x50&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&wgl=1&dt=1552842680356&bpp=22&bdt=955&fdt=24&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=687865738&dssz=22&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=144&ady=10&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeE|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=3769963683&ifi=1&uci=1.fvqg64vvsvyt&fsb=1&xpc=UmRWdgiTKA&p=https%3A//www.alternativenation.net&dtd=54:221 [Violation] 'load' handler took 299ms
common.bundle.880980e048a2432334f13013030456ac.js:1 [Violation] 'load' handler took 388ms
common.bundle.880980e048a2432334f13013030456ac.js:3 [Violation] 'message' handler took 461ms
outbrain.js:140 [Violation] 'resize' handler took 155ms

And finally, clicking the JRP icon yields 9 messages.
----- 1 error:
Error handling response: TypeError: Cannot read property 'insertBefore' of null
    at createSimplifiedOverlay (file:///C:/Users/Greg/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/dpamdgmnffodphoamchpmbclkpmccjga/3.3.7_0/content_script.js:2300:25)
    at file:///C:/Users/Greg/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/dpamdgmnffodphoamchpmbclkpmccjga/3.3.7_0/content_script.js:2046:13
----- 8 verbose:
[Violation] Forced reflow while executing JavaScript took 134ms
[Violation] Forced reflow while executing JavaScript took 36ms
VM812 adsbygoogle.js:17 [Violation] 'setTimeout' handler took 508ms
show_ads_impl.js:1 [Violation] 'setTimeout' handler took 52ms
[Violation] Forced reflow while executing JavaScript took 52ms
abg_lite.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
I @ abg_lite.js:1
Bc @ abg_lite.js:1
zc @ abg_lite.js:1
Ic @ abg_lite.js:1
Jc @ abg_lite.js:1
Hc @ abg_lite.js:1
Pc @ abg_lite.js:1
(anonymous) @ ads?client=ca-pub-5296172734705889&output=html&h=250&slotname=7889657381&adk=462315722&adf=1975853983&w=300&lmt=1552843427&guci=2.2.0.0.2.2.0.0&format=300x250&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&avail_w=587&wgl=1&dt=1552842680954&bpp=26&bdt=1553&fdt=M&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0%2C320x50%2C300x250&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=44729343&dssz=71&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=154&ady=1304&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&loc=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeEbr|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=1335172480&ifi=2&uci=2.di0hv8qok1p9&fsb=1&xpc=o5elPZURXa&p=https%3A//www.alternativenation.net&dtd=M:1
[Violation] Forced reflow while executing JavaScript took 120ms
ads?client=ca-pub-5296172734705889&output=html&h=250&slotname=7889657381&adk=462315722&adf=1975853983&w=300&lmt=1552843427&guci=2.2.0.0.2.2.0.0&format=300x250&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&avail_w=587&wgl=1&dt=1552842680954&bpp=26&bdt=1553&fdt=M&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0%2C320x50%2C300x250&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=44729343&dssz=71&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=154&ady=1304&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&loc=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeEbr|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=1335172480&ifi=2&uci=2.di0hv8qok1p9&fsb=1&xpc=o5elPZURXa&p=https%3A//www.alternativenation.net&dtd=M:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
F @ ads?client=ca-pub-5296172734705889&output=html&h=250&slotname=7889657381&adk=462315722&adf=1975853983&w=300&lmt=1552843427&guci=2.2.0.0.2.2.0.0&format=300x250&url=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&flash=0&avail_w=587&wgl=1&dt=1552842680954&bpp=26&bdt=1553&fdt=M&idt=-M&shv=r20190313&cbv=r20190131&saldr=aa&abxe=1&prev_fmts=0x0%2C320x50%2C300x250&nras=1&correlator=1732173573263&frm=20&pv=1&ga_vid=1142930150.1552754203&ga_sid=1552842680&ga_hid=1703545066&ga_fc=0&iag=0&icsg=44729343&dssz=71&mdo=0&mso=0&u_tz=-420&u_his=3&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=3&u_nmime=4&adx=154&ady=1304&biw=607&bih=714&scr_x=0&scr_y=0&eid=21060853%2C21063245&oid=3&ref=https%3A%2F%2Fgithub.com%2FZachSaucier%2FJust-Read%2Fissues%2F238&loc=https%3A%2F%2Fwww.alternativenation.net%2Fled-zeppelin-member-brutally-rejected-beatles-icon%2F&rx=0&eae=0&fc=1936&brdim=309%2C0%2C309%2C0%2C1536%2C0%2C1194%2C836%2C624%2C714&vis=1&rsz=||oeEbr|&abl=CS&ppjl=f&pfx=0&fu=16&bc=15&osw_key=1335172480&ifi=2&uci=2.di0hv8qok1p9&fsb=1&xpc=o5elPZURXa&p=https%3A//www.alternativenation.net&dtd=M:1

I hope this helps. Let me know if I can do anything else useful. 
Thanks.

**Comment by gshinton1** [comment] 2019-03-17 17:36
Forgot to say this:
If you think a simple solution would be upgrading to Windows 10, let me know; I'm planning on upgrading in the near future anyway.
Thanks.

**Comment by ZachSaucier** [comment] 2019-03-18 13:48
Thanks for the additional info! 

In reference to the dark theme being selected, can you please navigate to [JR's Options page](chrome-extension://dpamdgmnffodphoamchpmbclkpmccjga/options.html) and see which theme is currently being used (it's the one in italics) and let me know? Second, could you please check to see if the CSS for `default-styles.css` is the same as for `dark-theme.css`? There might have been an error when JR updated the stylesheets by overriding the default with the dark theme (but I think I should have fixed the root cause of this issue already in the most recent commit). 

On the [problematic page](https://www.alternativenation.net/led-zeppelin-member-brutally-rejected-beatles-icon/), can you try opening the console before opening JR, clearing it (using the clear button or `Ctrl` + `L`), then running JR? When I do that, I don't see any errors. It looks like most of the errors that you posted are from the original page, not JR. 

The last error is a very unexpected one given the nature of what is happening on that line in JR - it's in the lightbox portion of JRP. I also can't reproduce it.

Please use the most recent version of JRP, version 3.4.0, to test these sites.

**Comment by gshinton1** [comment] 2019-03-18 14:58
The CSS for default-styles.css was, in fact, identical to dark-theme.css. Replacing it with the copy in the repository fixes that problem. 

After updating to version 3.4.0, I only get one error on the [problematic page](https://www.alternativenation.net/led-zeppelin-member-brutally-rejected-beatles-icon/):
Error handling response: TypeError: Cannot read property 'insertBefore' of null
    at createSimplifiedOverlay (file:///C:/Users/Greg/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/dpamdgmnffodphoamchpmbclkpmccjga/3.4.0_0/content_script.js:2286:25)
    at getDomainSelectors (file:///C:/Users/Greg/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/dpamdgmnffodphoamchpmbclkpmccjga/3.4.0_0/content_script.js:2032:9)
    at continueLoading (file:///C:/Users/Greg/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/dpamdgmnffodphoamchpmbclkpmccjga/3.4.0_0/content_script.js:2407:5)
    at file:///C:/Users/Greg/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/dpamdgmnffodphoamchpmbclkpmccjga/3.4.0_0/content_script.js:765:9

Most other pages seem to behave normally. This is definitely an improvement. Also, you have forced me to learn a little about GitHub and style sheets. Thank you. 😊

**Comment by ZachSaucier** [comment] 2019-03-18 16:23
Hmm. That's still with the lightbox functionality, but I don't understand why it would be occurring and I can't reproduce it on my end. 

Let me know if this error continues to occur on other pages for you.

**Comment by ZachSaucier** [comment] 2019-03-20 19:28
Closing this, at least for now.

**Closed by ZachSaucier** 2019-03-20 19:28 UTC
Labels: bug
