### ISSUE TITLE
Doesn’t work on thesun.co.uk

### ISSUE THREAD

**Issue by JeffKang** [ZachSaucier/Just-Read#358] opened 2021-03-16 19:43 UTC
Hi there, I noticed that some incompatible websites are being tracked on the "Improve selection algorithm" thread.

I’d like to add:

https://www.thesun.co.uk/news/14276151/china-plans-high-tech-streets-spy-cams-inform-neighbours/

I however tried the “Select content to read” option for the first time, and was able to extract the right section after some trial and error.

Thanks for the great extension,

**Comment by ZachSaucier** [comment] 2021-03-16 19:56
Thanks for the report! I added it to the list of the relevant issue. 

Closing this as a duplicate of #331

**Closed by ZachSaucier** 2021-03-16 19:56 UTC
