### ISSUE TITLE
It's not working on this site. 

### ISSUE THREAD

**Issue by jdwoolington28** [ZachSaucier/Just-Read#332] opened 2020-11-09 20:30 UTC
**Describe the bug**
Does not include the body of the text in this blog posting. 

**To Reproduce**
1. Go to https://blog.drjoedispenza.com/the-role-of-brainwaves-in-meditation-part-i
2. Click on Just Read browser extension
3. See error

**Expected behavior**
Will not include the text of the blog post. 

**Please complete the following information:**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  86.0.4240.193

**Comment by ZachSaucier** [comment] 2020-11-09 20:33
Hey jdwoolington28. It seems to work just fine for me. Can you please provide more information on how to recreate the issue?

Also are you aware of [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode)? It lets you select the content when Just Read's auto selection fails.

**Comment by jdwoolington28** [comment] 2020-11-09 21:00
OK, I was not aware of user selection mode but I did find it and I was able to use it to get the page to show for me. Thank you!

**Comment by ZachSaucier** [comment] 2020-11-09 21:03
Closing due to a lack of reproduction. I'm glad I could help you learn about a helpful feature!

**Closed by ZachSaucier** 2020-11-09 21:03 UTC
Labels: bug
