### ISSUE TITLE
Display problems

### ISSUE THREAD

**Issue by chaulo** [ZachSaucier/Just-Read#2] opened 2016-05-17 12:33 UTC
Following our discussion on Just Read comments, I agree with you, following rechecking, that site 1 [link](http://www.liberation.fr/france/2016/05/10/apres-l-affaire-baupin-les-langues-se-delient_1451598?xtor=rss-450) and 3 [link](http://whowhatwhy.org/2016/05/09/wars-will-fought-21st-century/
) work almost normally. I don't know what happen the first time. And I agree with you for site 3 [link](http://www.marianne.net/nucleaire-les-tres-chers-amis-chinois-edf-100242737.html) that code is probably responsible.
But lot of web sites have bad code and I compared your extension with Reader, that I used with Firefox, and Clearly, that I used previously on Chrome before trying your extension. 
For example, your extension doens't display the introduction paragraph (I don't know the specific term in English) of site 1 article, which displays with Clearly.
On Reader, the introduction paragraph displays but not in bold and the title of the article has disappeared ! :-)
You will find attach screen captures 
– blank screen when quitting Just Read
– Liberation article display page with Just Read
– Liberation article display page with Clearly (in 2 parts)
![just_read_blank_screen](https://cloud.githubusercontent.com/assets/7276420/15322296/29ef5bdc-1c3c-11e6-8bf6-52f3daf11092.jpg)
![liberation_article_clearly_part2](https://cloud.githubusercontent.com/assets/7276420/15322295/29ef4a5c-1c3c-11e6-90ff-407ec6a1c83d.jpg)
![liberation_article_clearly_part1](https://cloud.githubusercontent.com/assets/7276420/15322297/29f09272-1c3c-11e6-8896-c8a7e2b87840.jpg)
![liberation_article_just_read](https://cloud.githubusercontent.com/assets/7276420/15322298/29f515d6-1c3c-11e6-8e37-e33f044b6e59.jpg)

And thanks for you concern about the quality of your extension.
GIlles Chauvain

**Comment by ZachSaucier** [comment] 2016-05-17 13:44
Hey GIlles and thanks again for taking the time to help me improve the extension

I just added [a commit](https://github.com/ZachSaucier/Just-Read/commit/0a912e3512a84228f01c4db2e4189bb5d3c7c255) to try and improve the text selection by first searching for any `<article>` elements which fixes the issue with [site 1](http://www.liberation.fr/france/2016/05/10/apres-l-affaire-baupin-les-langues-se-delient_1451598?xtor=rss-450) (though it retains some ugly text - a next step might be to parse that better) and also tries to select more generally if a threshold of total `<p>` elements are not selected to try and fix [site 2](http://www.marianne.net/nucleaire-les-tres-chers-amis-chinois-edf-100242737.html).

Selection is an area that I'm looking to improve further, so if you have any ideas for methodology of how to do so let me know!

One of my planned features to add to this extension is a "Use selected text" feature which would enable the user to specify what on a page should be shown. Keep an eye out for it - I hope to get it implemented sometime in the next week or two!

**Comment by ZachSaucier** [comment] 2016-05-17 13:52
As for your blank screen, I can't reproduce that effect (maybe it's a Mac thing? I'll check using my brother's Mac later this week). Is there any console errors that show when that occurs? And could you take a look at the HTML structure using the inspector to see if anything has changed?

What should be happening is only the iframe I'm adding to format the content should be removed. The original page should be left alone besides some temporary style changes

**Comment by chaulo** [comment] 2016-05-17 14:30
> Le 17 mai 2016 à 15:44, Zach Saucier - notifications@github.com <github.chaulo.7528e16fdf.notifications#github.com@ob.0sg.net> a écrit :
> 
> Hey GIlles and thanks again for taking the time to help me improve the extension
> 
Most of the readers have difficulties at displaying the « introduction » of an article. And probably most of the time the code of the site is not very good. 
> I just added a commit <https://github.com/ZachSaucier/Just-Read/commit/0a912e3512a84228f01c4db2e4189bb5d3c7c255> to try and improve the text selection by first searching for any <article> elements which fixes the issue with site 1 <http://www.liberation.fr/france/2016/05/10/apres-l-affaire-baupin-les-langues-se-delient_1451598?xtor=rss-450> (though it retains some ugly text - a next step might be to parse that better) and also tries to select more generally if a threshold of total <p> elements are not selected to try and fix site 2 <http://www.marianne.net/nucleaire-les-tres-chers-amis-chinois-edf-100242737.html>.
> 
> Selection is an area that I'm looking to improve further, so if you have any ideas for methodology of how to do so let me know!
> 
Sorry, I can’t help you about methodology. I stopped coding html site a long time ago and don’t know enough about good or bad coding of present web sites !
> One of my planned features to add to this extension is a "Use selected text" feature which would enable the user to specify what on a page should be shown. Keep an eye out for it - I hope to get it implemented sometime in the next week or two
> 
Not a bad idea, even if selecting a specific part of the text of an article can be tricky because of the layout structure.



I just compared a Wikipedia article with the 3 extensions. 
Here is the article :
https://en.wikipedia.org/wiki/1992_Yugoslav_People%27s_Army_column_incident_in_Tuzla <https://en.wikipedia.org/wiki/1992_Yugoslav_People's_Army_column_incident_in_Tuzla>

– Just Reader has no real problem with the main part of the article. But the sidebar table, on the right, is poorly displayed. And Just Reader displays even the « Bosnian War » list, at the end of the table, which is hidden by default in the Wikipedia article (and doesn’t display with Clearly of Reader).
– Clearly makes a good job at displaying the main part but skip totally the table.
– Reader (Firefox) displays the table first as a… table. And the main part of the article is well displayed.

I hope that can help. :-)


About the blank screen, I looked at the source code and the code of articles is still there !

**Comment by ZachSaucier** [comment] 2016-05-17 16:03
Sites like Wikipedia with their own major systems of styling are beasts to try and handle generically. Maybe a feature for user-installed domain-specific styling would be helpful (for when users use a domain a lot but don't want their changes to effect all other sites they apply the extension on).

As I believe the issue with the sites brought up have been addressed, I'm going to close this issue. If you find other sites that you believe should work with the extension but don't, or have suggestions for how you think the extension could be improved, please let me know! 

Thanks again for your contribution

**Closed by ZachSaucier** 2016-05-17 16:03 UTC

**Comment by chaulo** [comment] 2016-05-19 11:12
Following our conversation, I did understand the case of the blank screen. As with other extensions, I used to quid the « read » mode by clicking again on the extension icon. Doing that you get a blank screen. Quitting by clicking the x case on the page doesn’t do that.

Another suggestion : you could streamline the article by suppressing menus which are not useful in read mode.
For example, in this article :
http://rue89.nouvelobs.com/2016/05/19/ressources-inhumaines-politis-flingue-systeme-free-264076 <http://rue89.nouvelobs.com/2016/05/19/ressources-inhumaines-politis-flingue-systeme-free-264076>
suppressing :
Se connecter <http://rue89.nouvelobs.com/user/login>
Créer son compte <http://rue89.nouvelobs.com/> <http://tempsreel.nouvelobs.com/> <http://rue89.nouvelobs.com/>
Les+lus <http://rue89.nouvelobs.com/views>
Le meilleur du web <http://rue89.nouvelobs.com/vigie>
Les partis pris <http://rue89.nouvelobs.com/parti-pris>
En images <http://rue89.nouvelobs.com/image>
Extra <http://rue89.nouvelobs.com/extra>
Au hasard <http://rue89.nouvelobs.com/random>
Les blogs <http://rue89.nouvelobs.com/blogs>
MOOC Rue89 <http://mooc.rue89.com/>

**Comment by ZachSaucier** [comment] 2016-05-19 13:41
Good call on the blank screen. I caught an error in how I was attempting to handle the button being clicked twice. It was originally supposed to just console log an error message, but I have [updated it](https://github.com/ZachSaucier/Just-Read/commit/53b36545cc4b364e15a74852cefa1ca449f2d113) to close the article (granted the article has loaded) because I like that functionality.

As for stripping menus like that, I agree that it would be helpful, but it is incredibly difficult to do in practice. If you'd like, you can create a [new issue](https://github.com/ZachSaucier/Just-Read/issues/new) requesting better parsing, but I can't promise I'll implement it as it increases the complexity of the project exponentially (I would need to analyze the HTML attributes and compare it to a list of ones to strip that I make or something similar)

**Comment by ZachSaucier** [comment] 2016-05-19 17:36
I may still do some type of text highlighting selection, but in talking with my friend I may be able to use user selection to remove parts of articles like the menu after it has been selected. We shall see 😃

**Comment by chaulo** [comment] 2016-05-19 18:02
> Le 19 mai 2016 à 19:37, Zach Saucier - notifications@github.com <github.chaulo.7528e16fdf.notifications#github.com@ob.0sg.net> a écrit :
> 
> I may still do some type of text highlighting selection, but in talking with my friend I may be able to use user selection to remove parts of articles like the menu after it has been selected. We shall see 😃
> 
I'm not sure about user selection to remove a menu since it will be faster to jump after the menu than to select it and click on a remove button.

BTW, another suggestion, you could offer one or two preset stylesheets with, for example, beige background (like Clearly or Reader) or/and sans serif font.

**Comment by ZachSaucier** [comment] 2016-05-19 20:57
I [added](https://github.com/ZachSaucier/Just-Read/commit/41403183e4330baf803b60269308e97923513af2) a select-to-read feature that is able to be used by right clicking the extension button and selecting "Select text to read" or by using the shortcut (the default is CTRL+SHIFT+K). Let me know how you like it!

I think I may also add a delete functionality after the text is selected, but not today

**Comment by chaulo** [comment] 2016-05-23 13:10
Hello,

Me again  ! :-)
You should have a look at the parsing of this article which display unecessary icons in full size
http://www.pcadvisor.co.uk/review/headphones/inateck-aries-review-3636917/ <http://www.pcadvisor.co.uk/review/headphones/inateck-aries-review-3636917/>
To compare with the parsing by the extension Clearly.

Best
Loïc
