### ISSUE TITLE
just read gives empty body on blog.blackswanltd.com

### ISSUE THREAD

**Issue by Wes4329** [ZachSaucier/Just-Read#405] opened 2022-09-20 19:02 UTC
When I use Just Read on the URL:
https://blog.blackswanltd.com/the-edge/does-eye-contact-help-or-hurt-a-negotiation?utm_campaign=The+Edge+-+Newsletters&utm_medium=email&_hsmi=226620115&_hsenc=p2ANqtz-_u8eEhbKDIT2QH9597rYc2LRUUgFIfgFYAKZndd-ShHy5jrj36iCiCj2M59p9PF69AcyGxeAej5v5LqvNk1u2yeCTTLw&utm_content=226620115&utm_source=hs_email&jr=on

Then I only get a header and footer, no content. The resulting page is:
Unknown date
Barbara Thomas
Does Eye Contact Help or Hurt a Negotiation?
Viewed using [Just Read](https://justread.link/)

[Report an error](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20)

**Comment by zs-stripe** [comment] 2022-09-20 19:28
Hey Wes and thanks for reaching out.

I'll investigate this issue more deeply to try and find the root cause later. For now, you should be able to use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content within Just Read.

**Comment by ZachSaucier** [comment] 2022-09-21 22:55
This is an edge case where more paragraphs are used in the article meta section than the actual article section. As such, it's the same core issue as #331. I'm going to close this issue as it's a dupe!

**Closed by ZachSaucier** 2022-09-21 22:55 UTC
