### ISSUE TITLE
text lossing 

### ISSUE THREAD

**Issue by TomishaCom** [ZachSaucier/Just-Read#231] opened 2019-02-17 19:16 UTC
>
![t3n de_news_eigentlich-github-472886_ 1](https://user-images.githubusercontent.com/47674859/52917919-e52d4580-32f0-11e9-9f7f-fa8a12d10a5f.png)
![t3n de_news_eigentlich-github-472886_](https://user-images.githubusercontent.com/47674859/52917920-e52d4580-32f0-11e9-93cc-e1a39808a670.png)

 Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment] 2019-02-17 19:18
As stated in the text, **please include the relevant URL** so I can test this out for myself and try to figure out the issue. Otherwise I won't be able to help you.

**Comment by TomishaCom** [comment] 2019-02-17 19:53
https://t3n.de/news/eigentlich-github-472886/ 

all reading text from t3n.de

**Comment by ZachSaucier** [comment] 2019-02-17 21:50
At its core, the issue is the same as #95. As such I'm going to add this domain to the list in that issue and close this issue as a duplicate. 

Thanks for posting!

**Closed by ZachSaucier** 2019-02-17 21:50 UTC
Labels: duplicate

**Comment by TomishaCom** [comment] 2019-02-18 09:07
the pictures are missing too.
