### ISSUE TITLE
Still see context menu entry although it's disabled

### ISSUE THREAD

**Issue by kkumlien** [ZachSaucier/Just-Read#172] opened 2018-08-03 12:48 UTC
See screenshots of my configuration and what I see in the context menu.

<img width="551" alt="screen shot 2018-08-03 at 1 46 23 p m" src="https://user-images.githubusercontent.com/6783174/43643614-c15fa472-9723-11e8-9ff4-d9dd2c816199.png">
<img width="372" alt="screen shot 2018-08-03 at 1 45 00 p m" src="https://user-images.githubusercontent.com/6783174/43643615-c17e2442-9723-11e8-9d20-58af3031bb32.png">

**Comment by ZachSaucier** [comment] 2018-08-03 19:15
Hello and thanks for the report! 

I can't seem to reproduce this error. I'll test on a Mac when I have access to one.

**Comment by ZachSaucier** [comment] 2018-08-12 19:40
I can't reproduce this in any environment I've tested on, including Macs. Is this error still happening for you?

**Comment by kkumlien** [comment] 2018-08-14 00:37
Thanks Zach!
Kind of. I noticed that deactivating that worked as expected after I restarted the browser.
But now it seems I'm unable to activate it even if I restart... It's fine with me as I want it deactivated.
It's weird, as the other 3 flags (also related to the context menu) work fine even without restarting.

FYI I'm running Just Read 1.2.5 on Chrome 68.0.3440.106 (Official Build) (64-bit) on macOS High Sierra 10.13.6 (17G65).
Let me know if I can provide any more info.

Cheers

**Comment by ZachSaucier** [comment] 2018-08-14 02:12
They shouldn't require restarting... 

I can't see any difference in the code between that setting and the others after triple checking it. I guess I'll close this issue for now since I can't reproduce it and it's not bothering you any longer.

**Closed by ZachSaucier** 2018-08-14 02:12 UTC
Labels: bug
