### ISSUE TITLE
GUI color selector

### ISSUE THREAD

**Issue by WimDeBacker** [ZachSaucier/Just-Read#201] opened 2018-10-05 09:21 UTC
Hi,

Another problem with the GUI
When I try to change the color, I can not change the HUE.
There seems to be a black bar on the right to change the hue.
![screen shot 10-05-18 at 11 20 am](https://user-images.githubusercontent.com/5185126/46527208-d0479c80-c890-11e8-9435-a1787378b302.PNG)

Wim

> Thanks for wanting to help improve Just Read! 
> 
> Looking through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) may help you with your request. Please look through [the existing posts](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment] 2018-10-05 12:33
Thanks for the report! I can't reproduce this on the sites that I'm testing on, but I know the GUI has some CSS issues depending on the site. Does this happen for you on every domain or only some? If only some, please provide a URL for me to test with.

**Comment by ZachSaucier** [comment] 2018-10-18 12:35
Closing this at least until more information is given.

**Closed by ZachSaucier** 2018-10-18 12:35 UTC
Labels: bug
