### ISSUE TITLE
Add syntax highlighting to code chunks

### ISSUE THREAD

**Issue by bezirganyan** [ZachSaucier/Just-Read#196] opened 2018-09-29 15:54 UTC
It would be nice to have code recognition and syntax highlighting for the pages which have code chunks.

P.S really like the extension, it's clean and nice

**Comment by ZachSaucier** [comment] 2018-09-29 15:58
Hello and thanks for the post. This seems to be a duplicate of #142, so I'm going to close it as such. 

I'm glad you like the extension!

**Closed by ZachSaucier** 2018-09-29 15:58 UTC
Labels: duplicate
