### ISSUE TITLE
Article cut off

### ISSUE THREAD

**Issue by neilmehtablink** [ZachSaucier/Just-Read#83] opened 2017-07-13 18:08 UTC
http://www.consumerreports.org/pharmacies/get-a-pharmacy-discount-with-medicare/

**Comment by ZachSaucier** [comment] 2017-07-13 18:12
Thanks for the report! 

This is a duplicate of #32, so I'll add it to the list of problematic sites and close this issue as a duplicate.

**Closed by ZachSaucier** 2017-07-13 18:12 UTC
Labels: duplicate
