### ISSUE TITLE
Just Read opens itself after I close it when site is in my auto-run list

### ISSUE THREAD

**Issue by Orlinky** [ZachSaucier/Just-Read#361] opened 2021-03-24 16:01 UTC
Hello,

**Describe the bug**
I can't close Just Read on Firefox, it closes and reopens immediately. 

**Additional context**
This seems to only happen to pages on the auto-run domain list. 
When i start Just Read manually this doesn't happen, it also doesn't happen on Chrome with the same configuration.

**Environment**
I am using the latest versions of macOS, Firefox and Chrome.

**Comment by ZachSaucier** [comment] 2021-03-24 16:03
Hey Orlinky.

I'm guessing that you have that site in your "Auto-run domain list"? 

I'm also guessing that you have "Remove the original page's content once the Just Read view has opened (better performance but loses original page load if JR view closed)." checked. Is that true?

You should be able to fix the issue by either removing the site from your auto-run list or unchecking that box.

**Comment by ZachSaucier** [comment] 2021-03-24 16:05
Essentially what is happening is that when you close the Just Read view, Just Read refreshes the page (because all of the original content was removed). But since it's in your auto-run list it starts Just Read again.

You can disable the functionality that causes Just Read to get rid of the original page content and it should work. But your Just Read view might be a little more sluggish on some web pages.

**Comment by Orlinky** [comment] 2021-03-24 16:08
As i said this only happens to websites on the auto-run domain list but i do not have "Remove the original page's content once the Just Read view has opened (better performance but loses original page load if JR view closed)." checked so it must be something else.

Everything is unchecked in my settings.

**Comment by ZachSaucier** [comment] 2021-03-25 00:56
I see. Thanks for the report. I can reproduce the issue in Firefox.

Debugging, it looks like Firefox sends the `chrome.tabs.onUpdated` event if you remove the Just Read iframe from the page, which makes no sense because no navigation has occurred... 

I had to add another message to the background script to make sure that the "onUpdate" doesn't fire within a set amount of time after the close button. Should be fixed in the next version. I'll push it to the webstore now.

**Closed by ZachSaucier** 2021-03-25 00:56 UTC
Labels: bug
