### ISSUE TITLE
Not working on blogspot.com

### ISSUE THREAD

**Issue by the21st** [ZachSaucier/Just-Read#191] opened 2018-09-03 19:39 UTC
E.g. http://reducing-suffering.blogspot.com/2012/08/pain-vs-suffering-and-animals-vs-humans.html

**Comment by ZachSaucier** [comment] 2018-09-03 19:41
Thanks for the report! The cause for this is the same as #94, so I'm going to close this issue as a duplicate. As mentioned in that issue, you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to work around this issue.

**Closed by ZachSaucier** 2018-09-03 19:41 UTC
Labels: duplicate
