### ISSUE TITLE
Unable to make comments

### ISSUE THREAD

**Issue by neelanjans** [ZachSaucier/Just-Read#347] opened 2020-12-09 09:53 UTC
Hi,

I am unable to make comments upon selecting a text in 'Just Read' mode. I see the button appearing on the side of the paragraph but when I click on it, nothing happens and the button also disappears.

**Comment by ZachSaucier** [comment] 2020-12-09 13:03
Hey neelanjans, thanks for reaching out.

Can you please provide additional information:

- Have you purchased Just Read Premium?
- What browser are you using?
- What operating system are you on?
- If you press F12 to open up the developer console, what errors show up?
- Do you have a zoom level higher than 100% in your OS settings or browser settings? 
- Are you using Just Read's default theme?

**Comment by ZachSaucier** [comment] 2020-12-12 13:24
Closing this until more details are given.

**Closed by ZachSaucier** 2020-12-12 13:24 UTC
Labels: bug

**Comment by oneninetyeight** [comment] 2020-12-15 05:14
Hi there!#

I've encountered a similar issue. What I've discovered though, is that in my case, the comment window pops up at the bottom of the page. I use Chrome and at first thought this might be an issue with another plugin such as uBlock. I made a screen recording for you to observe the behavior which you can [look at here](https://www.sbx.pw/BluQx5zk). As a new premium user with Just Read I also created [a shared link](https://justread.link/xmMDCfTm_), where the comment can be seen at the bottom.

My answers to your questions:
- Have you purchased Just Read Premium?
**Yes**
- What browser are you using?
**Chrome Version 87.0.4280.88 (Official Build) (x86_64)**
- What operating system are you on?
**Mac OS 10.15.7**
- If you press F12 to open up the developer console, what errors show up?
**a few, mostly related to blocking of ads and paywalls**
- Do you have a zoom level higher than 100% in your OS settings or browser settings?
**No, 90%**
- Are you using Just Read's default theme?
**Yes**

**Comment by ZachSaucier** [comment] 2020-12-15 20:50
Hey @oneninetyeight. I'm pretty sure that's because you're _not_ actually using the default theme. It looks like you're using the _old_ version of the default theme. You should be able to check by right clicking the Just Read icon, going to the Options page, and seeing which theme is currently being used. If you switch back to the default theme I believe it should resolve your issue. The new version of Just Read has selectors that are a little different than the old ones.

**Comment by oneninetyeight** [comment] 2020-12-16 11:06
ok, my bad, you're right! I guess I somehow duplicated the oder default theme and I was using that. The issue is now resolved 👍  Thanks!
