### ISSUE TITLE
Error message after updating to Premium

### ISSUE THREAD

**Issue by Swifty477** [ZachSaucier/Just-Read#174] opened 2018-08-06 22:33 UTC
I have the premium version.  I use Windows 10.  When I try to use the new Premium Just Read, I get sent to a web page that says I have "too many shared articles," and I am prompted to go to some home page to clear them.  I have never had a "save" function that I know about for Just Read.  I have not been able to use the premium version yet because I always get the same message, whether it's an article from CNN or some other site.  I've tried a number of different sites and always get the same error message.  

-- Swifty477

**Comment by ZachSaucier** [comment] 2018-08-06 22:37
Thanks for the report. So sorry it hasn't worked for you yet. 

Have you tried sharing any articles in Just Read's format yet?

**Comment by ZachSaucier** [comment] 2018-08-06 22:41
The link on the "too many shared pages" notification was incorrect - it should point to https://justread.link/dashboard

I uploaded a fix to the Chrome store now but it will take some time to propogate.

You still shouldn't be seeing this message unless you have over 100 shared pages existing. Have you shared that many pages thus far?

**Comment by ZachSaucier** [comment] 2018-08-06 22:50
Did you try to share this page? https://en.wikipedia.org/wiki/1987_Fijian_coups_d%27%C3%A9tat

**Comment by ZachSaucier** [comment] 2018-08-06 22:53
Also, do you have the old version of Just Read still installed?

**Comment by ZachSaucier** [comment] 2018-08-06 22:57
And one more question: are you signed into multiple Google accounts in Chrome?

**Comment by Swifty477** [comment] 2018-08-06 23:35
No, I am not.   
  
  
  

  
  

  
  
>

**Comment by Swifty477** [comment] 2018-08-06 23:36
I removed the *old* Just Read from the, you know, task bar of icons upper-right of Chrome.    Maybe that isn’t enough?
  

  
Thanks for your help.    — John
  

  
  

  
  
>

**Comment by Swifty477** [comment] 2018-08-06 23:36
No, I haven’t shared any pages.    
  

  
  

  
  
>

**Comment by Swifty477** [comment] 2018-08-06 23:37
No, I have not. I have not made it to that.    I’ve been using the non-Premium Just Read and if there was the ability to share those pages, I didn’t know about it.    
  
  

  
— John
  
  

  
  

  
  
>

**Comment by ZachSaucier** [comment] 2018-08-06 23:40
Sorry for the stream of messages. I was investigating potential issues and posting them as I thought of them. 

So to be clear: You click the Just Read button and then the error message of "You have too many shared articles" appears? You're not able to read the article or click any of the buttons?

**Comment by ZachSaucier** [comment] 2018-08-07 00:56
This is high priority because it may affect other users. Can you tell me what you see on [this page](https://justread.link/dashboard)?

**Comment by ZachSaucier** [comment] 2018-08-07 16:58
Are you seeing what [this post](https://github.com/ZachSaucier/Just-Read/issues/176) describes?

**Comment by Swifty477** [comment] 2018-08-10 22:10
That is absvolutely correct.  Please excuse the lateness of my reply.

**Comment by Swifty477** [comment] 2018-08-10 22:13
Again, sorry for late response.  Here's what I see when I click on the link
you provide:

[image: Capture what I see as of 08.10.2018.PNG]

**Comment by ZachSaucier** [comment] 2018-08-11 03:40
I'm afraid your image link didn't work. Can you please try again? Providing the plain image URL is fine.

**Comment by ZachSaucier** [comment] 2018-08-12 19:36
This is still happening for you, every time you try to load Just Read?
If so, can you please open the Console by pressing F12, try running Just Read, and then see what error messages appear in the Console? Please share them if you see any.

**Comment by ZachSaucier** [comment] 2018-08-16 13:07
I'm going to close this issue as a duplicate of #176 since they're the same issue. Please post any additional relevant information to that one!

**Closed by ZachSaucier** 2018-08-16 13:07 UTC
Labels: bug

**Comment by Swifty477** [comment] 2018-08-21 18:06
Zach!  I just wanted to let you know I just tried my "Just Read" icon and
it worked!  You must have done something.  Thank you very much!

-- John

**Comment by ZachSaucier** [comment] 2018-08-21 18:07
I'm so glad that it did!

**Comment by Swifty477** [comment] 2018-08-21 18:17
And the problem just happened again.  Too bad.

**Comment by ZachSaucier** [comment] 2018-08-21 18:19
What web page is it happening on?

And how old is your computer? What sort of internet connection do you have?

**Comment by ZachSaucier** [comment] 2018-08-28 13:32
I think I've fixed this problem, but it will take some time for the change to propagate. After your version has updated to JRP version 3.0.10, can you please confirm that the change I made fixes the issue?
