### ISSUE TITLE
Prevent sounds on main page even after Just Read is activated

### ISSUE THREAD

**Issue by wanderingstan** [ZachSaucier/Just-Read#272] opened 2019-10-02 13:57 UTC
**Describe the bug**
On some websites, background audio will play after some delay even when Just Read is activated. (Not sure if this is bug or feature request, but feels like a bug if content (even if audio) is able to get around the extension.)

**To Reproduce**
1. Go to https://www.cbsnews.com/news/china-spy-arrested-in-california-by-federal-bureau-of-investigation-edward-peng-charged-with-espionage/
2. Click on Just Read extension button for clean view of page
3. Scroll down. Highlight some text.
4. Audio from video will play after some delay

**Expected behavior**
Audio should not play while in Just Read mode

**Please complete the following information:**
 - OS: MacOS
 - Browser: Chrome
 - Version 78.0.3904.34

**Comment by ZachSaucier** [comment] 2019-10-02 14:05
Hey and thanks for the report.

It's not really a _bug_ in the sense that this is the intended behavior currently. Just Read is built to run after all content is loaded, including media. So currently Just Read is setup to pause all videos and audio from playing when Just Read is initiated but Just Read currently does nothing related to the original page once Just Read is open (until Just Read is closed).

I guess it makes sense to add this functionality, though it may be tricky to properly watch for any audio/video files being played (or even created) _after_ Just Read has already been created but only on the main page. 

I'm open to a PR that adds this functionality but may not get around to doing it myself for a while since I have little time to work on JR these days.

**Comment by wanderingstan** [comment] 2019-10-02 14:23
Cool--I wasn't sure what the intended scope of Just Read was.

I may look into doing that PR, tho its been a while since I did extensions. I did a quick search for "mute all audo on page" and —lo and behold!— I think the top result is a SO answer from you, @ZachSaucier  :) 
https://stackoverflow.com/a/37218500/59913
Seems it would be appropriate to use that code in the PR, then!

**Comment by ZachSaucier** [comment] 2019-10-02 14:26
Hah, yes. I already use that code to mute the elements in JR. The bigger trouble is writing the appropriate event listeners to watch for any audio or video elements being played including ones that haven't been created yet, as I mentioned above. The actual pausing is the easy part can you can make use of those functions.

`content_script.js` is the only file you'd need to edit, along with updating the version in the `manifest.json` file.

**Comment by ZachSaucier** [comment] 2019-11-28 17:26
I am closing this due to it being out of scope for what I intend for JR and don't think it's worth my time of adding. But I'm open to a PR that supports this.

**Closed by ZachSaucier** 2019-11-28 17:26 UTC
Labels: enhancement
