### ISSUE TITLE
Just-Read doesn't work with The Independent newspaper's website

### ISSUE THREAD

**Issue by ghost** [ZachSaucier/Just-Read#198] opened 2018-10-03 23:48 UTC
If you open any article on The Independent newspaper's website (e.g. [here](https://www.independent.co.uk/news/business/news/italy-deficit-eurozone-debts-bond-yields-five-star-league-giovanni-tria-a8566461.html)), and click the Just-Read icon, you get the following message: "Aw snap! Something went wrong when displaying the webpage." The problem doesn't occur on any other newspaper's website as far as I know. Please could you fix this?

**Comment by ZachSaucier** [comment] 2018-10-04 14:38
Interesting. I'm guessing this isn't technically a problem with JR - it's likely a problem with the site. But I'll investigate and see if I can see what's going on and maybe work around it.

**Comment by ZachSaucier** [comment] 2018-10-05 12:44
I was able to reproduce this error yesterday but no longer can. Can you see if it still is an issue on your side?

**Comment by ZachSaucier** [comment] 2018-10-05 12:47
I can only reproduce this error when dev tools is not open... So I have no idea how I'm supposed to debug the issue when I can't use dev tools, haha. As such this issue is likely to not be fixed unless someone can figure out how to debug it.

**Comment by DaveRado** [comment] 2018-10-05 21:34
I am still getting the error.

Dave

**Comment by Dave-Rado** [comment] 2018-10-05 21:42
I am still getting the error.

Dave

**Comment by ZachSaucier** [comment] 2018-11-21 17:37
This issue no longer occurs for me. Can you please confirm if JR works or not on this website for you?

**Comment by ZachSaucier** [comment] 2018-12-06 00:17
Closing since it seems fixed for me.

**Comment by Dave-Rado** [comment] 2018-12-06 01:43
Some pages work now but others do not. [Here's one that still doesn't work.](https://www.independent.co.uk/arts-entertainment/films/reviews/peterloo-review-film-mike-leigh-massacre-drama-movie-release-manchester-a8612901.html). It gives the "Aw, Snap!" error message when you click on the Just Read button.

**Comment by ZachSaucier** [comment] 2019-03-24 14:19
Interestingly, the problematic page that you link, @Dave-Rado, didn't work for me at the time but now does. Can you confirm this on your side? Also, can you find any other pages that don't work on their website?

**Comment by Dave-Rado** [comment] 2019-03-24 16:34
Hi ZachSaucier

The problem seems to be fixed now.

Thanks

Dave

**Comment by ZachSaucier** [comment] 2019-03-24 17:14
Cool. I'm going to close this again until someone posts another issue with it.

**Closed by ZachSaucier** 2019-03-24 17:14 UTC
Labels: bug
