### ISSUE TITLE
Vimium keyboard shortcuts stop working in read mode

### ISSUE THREAD

**Issue by infokiller** [ZachSaucier/Just-Read#24] opened 2016-12-02 10:29 UTC
When the page is switched to read mode, Vimium (https://github.com/philc/vimium) stops working.
Not sure if this is related to Just Read or Vimium.

Other than that, great extension! Thanks!

**Comment by ZachSaucier** [comment] 2016-12-02 12:57
This is likely due to the Just Read format using a dynamically created iframe, which I doubt that Vimium takes into account when applying its listeners. As such, it can't be fixed on my end, only the extension that attaches the listeners (Vimium).

**Closed by ZachSaucier** 2016-12-02 12:57 UTC

**Comment by infokiller** [comment] 2016-12-02 13:50
Thanks for looking into it!
I'll wait for Vimium's devs response on this.

**Comment by ZachSaucier** [comment] 2016-12-19 19:26
I just created a more general issue for the cause of this problem: #29
