### ISSUE TITLE
Support for using Annotation extensions

### ISSUE THREAD

**Issue by faizanahemad** [ZachSaucier/Just-Read#18] opened 2016-10-30 16:59 UTC
It would be great to have support for annotation extensions like [Diigo](https://chrome.google.com/webstore/detail/diigo-web-collector-captu/pnhplgjpclknigjpccbcnmicgcieojbh) or [Scrible](https://www.scrible.com/). 

Essentially there are extensions which help in annotating the page, me and many of my peers annotate the page and later save it. When we use Just-read we can't annotate the page. We are trying to get functionality like Evernote webclipper by using 2 extensions, one to remove clutter and one to annotate. These extensions work great separately but together they don't seem to work.

**Comment by ZachSaucier** [comment] 2016-10-30 17:10
Hello Faizan,

As I commented in #8 which requests practically the same thing, what Just Read generates is simply an iframe with no specific URL attached to it, pulling content from the main page. As such, it's up to the annotation extension to detect that this iframe has been created and handle being able to annotate it. You should post on their support/feature forums requesting this ability. If they need something from me, let me know (but they shouldn't).

The only thing I could do on the Just Read side would be to recreate all of the functionality of these extensions, but that is currently out of scope for this project.

**Closed by ZachSaucier** 2016-10-30 17:10 UTC
Labels: enhancement

**Comment by ZachSaucier** [comment] 2016-11-16 17:33
After thinking about this some more, I've decided to start work on a paid version of Just Read. See #20 for more details

**Comment by ZachSaucier** [comment] 2016-12-19 19:25
I just created a more general issue for the cause of this problem: #29

**Comment by ZachSaucier** [comment] 2018-08-06 01:52
There is now support for other extensions such as the ones discussed here in the shared version of Just Read pages. See [this post](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-add-annotations-and-comments) for highlighting and annotations inside of Just Read Premium and see [this post](https://github.com/ZachSaucier/Just-Read/#q-x-extension-doesnt-work-with-the-just-read-version-of-my-page-how-can-i-get-it-to-work) about support for other extensions within the shared version of JR pages.
