### ISSUE TITLE
Not all text displayed, missing first 2 paragraphs

### ISSUE THREAD

**Issue by ajmich54** [ZachSaucier/Just-Read#316] opened 2020-05-17 18:42 UTC
First two paragraphs are missing.

https://www.washingtonpost.com/nation/2020/05/16/obama-commencement-speech-2020/

 - OS: MacOS Catalina v10.15.4
 - Browser: Chrome
 - Version: 81.0.4044.138

**Comment by ZachSaucier** [comment] 2020-05-18 12:25
Hey and thanks for taking the time to report. Just Read seems to select the whole page's content for me. What are you seeing?

Also, are you aware of Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode)?

**Comment by ajmich54** [comment] 2020-05-18 19:01
Hi... thx for responding.  This behavior is happening with many articles at
The Washington Post site.  Here is another example:

https://www.washingtonpost.com/technology/2020/05/18/facebook-google-work-from-home

This is what I am seeing:

[image: Screen Shot 2020-05-18 at 2.52.59.png]

**Comment by ZachSaucier** [comment] 2020-05-18 19:05
This is a duplicate of #95. User user selection mode to work around it.

**Closed by ZachSaucier** 2020-05-18 19:05 UTC
Labels: bug
