### ISSUE TITLE
Enable pop ups of dictionary.

### ISSUE THREAD

**Issue by jvaldiviezo9** [ZachSaucier/Just-Read#310] opened 2020-04-26 04:36 UTC
**Is your feature request related to a problem? Please describe.**
I tend to use a lot the Google dictionary (https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja?hl=en), however, I can see that when the reading mode is active, the highlight of the word doesn't trigger the pop up inside the read mode.

**Describe the solution you'd like**
That at the moment of highlight the word the pop up appears as usual.

**Describe alternatives you've considered**
/// doesn't apply ///

**Additional context**

![image](https://user-images.githubusercontent.com/18518204/80297933-76961400-874d-11ea-803e-e1a41b7b829b.png)
![image](https://user-images.githubusercontent.com/18518204/80297936-8b72a780-874d-11ea-973c-b62a1221ed13.png)

**Comment by ZachSaucier** [comment] 2020-04-26 12:17
Duplicate of #29. See that thread for more info.

**Closed by ZachSaucier** 2020-04-26 12:17 UTC
Labels: enhancement
