### ISSUE TITLE
Cannot edit theme in Edge

### ISSUE THREAD

**Issue by rmwarren** [ZachSaucier/Just-Read#345] opened 2020-12-02 16:33 UTC
Premium user, just added the new version.

When I attempt to edit the theme in Edge the controls are only partially rendered and obscured by the icons in the upper right-hand corner of the browner window. Images attached.

![image](https://user-images.githubusercontent.com/6060965/100901557-f299cc80-3491-11eb-8711-f6af25ebf335.png)
![image](https://user-images.githubusercontent.com/6060965/100901591-fa597100-3491-11eb-90b8-c71e2eac3fb8.png)

Only way to remove is to reload the page.

**Comment by ZachSaucier** [comment] 2020-12-02 16:57
Hey rmwarren, thanks for the report. I'll investigate it when I get some time. In the mean time you should be able to edit your theme via CSS in Just Read's options. Are you able to do that?

Sorry for the trouble!

**Comment by ZachSaucier** [comment] 2020-12-02 23:23
I'm unable to reproduce this issue in Edge or any other browser. Is it an issue on _every_ webpage or just some? Are you using one of Just Read's default themes or a custom theme?

**Comment by rmwarren** [comment] 2020-12-03 15:48
Zach, it’s happening in both Chrome and Edge, multiple different web pages and I have made no modifications to the default theme. Open to doing a screen share if that would help you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ZachSaucier** [comment] 2020-12-03 16:58
Before we do that, could you please open up the console (F12) and share any errors that show when this occurs?

**Comment by rmwarren** [comment] 2020-12-03 18:59
Here you  go.

[cid:image002.png@01D6C97C.8D24DFA0]

I tried to run it on the WSJ page to give you another example, this time the add-in itself didn’t work. Opend the page, clicked Just Read and nothing much happened. Different error messages:

[cid:image005.png@01D6C97C.8D24DFA0]

Went to same page in Edge, same result:

[cid:image009.png@01D6C97C.8D24DFA0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ZachSaucier** [comment] 2020-12-03 19:18
It doesn't look like your images transferred properly. Can you please post on GitHub, not reply via your email?

**Comment by rmwarren** [comment] 2020-12-03 20:42
![image](https://user-images.githubusercontent.com/6060965/101085867-0de20600-357e-11eb-9a4a-aa4cbcb79daa.png)
![image](https://user-images.githubusercontent.com/6060965/101085883-133f5080-357e-11eb-9c03-234d1a5721a9.png)
![image](https://user-images.githubusercontent.com/6060965/101085901-19cdc800-357e-11eb-86a7-ac887f5b2992.png)

**Comment by rmwarren** [comment] 2020-12-03 20:43
![image](https://user-images.githubusercontent.com/6060965/101086040-4c77c080-357e-11eb-8a9f-beacf588426e.png)
![image](https://user-images.githubusercontent.com/6060965/101086061-51d50b00-357e-11eb-9471-7a427ec4a2e8.png)
![image](https://user-images.githubusercontent.com/6060965/101086079-5699bf00-357e-11eb-9d4d-b2a95eaa998f.png)

**Comment by ZachSaucier** [comment] 2020-12-03 22:46
Thanks for the images. I was able to reproduce and fix one error based on your screenshots: The error would only happen on certain pages and it would prevent Just Read from opening entirely. 

I uploaded a new version (5.0.9) to the Chrome store. It should reach you in the next day. Once it has updated would mind trying again?

I am still not able to reproduce the issue related to the theme editor not working. Can you please try using the theme editor on this page and see if it works? https://text.npr.org/942229249

**Comment by rmwarren** [comment] 2020-12-04 15:40
Zach, video of the theme issue:

https://www.youtube.com/watch?v=ZY1B2sJBY-I

**Comment by ZachSaucier** [comment] 2020-12-04 21:48
Maybe it's a conflicting extension. Would you mind:

1. Right click the Just Read icon and then click "Manage Extensions". 
2. Make sure "Developer mode" is checked in the top right.
3. Check "Allow in incognito".
4. Test Just Read on the text.npr site I linked to above.

If that doesn't work, maybe you could try reinstalling Just Read?

**Comment by ZachSaucier** [comment] 2020-12-12 13:24
Closing this until more details are given since I can't reproduce it.

**Closed by ZachSaucier** 2020-12-12 13:24 UTC
Labels: bug
