### ISSUE TITLE
Half-baked article

### ISSUE THREAD

**Issue by ycgambo** [ZachSaucier/Just-Read#168] opened 2018-07-17 10:22 UTC
Missing starting part of content [on this site](http://www.phpinternalsbook.com/php7/internal_types/strings/zend_strings.html#simple-use-case)

**Comment by ZachSaucier** [comment] 2018-07-17 12:53
Thanks for the report! This is a dupe of #95. Closing this issue and adding this domain to the list of problematic sites on the dupe issue.

**Closed by ZachSaucier** 2018-07-17 12:53 UTC
Labels: duplicate
