### ISSUE TITLE
doesn't work on autoblog.com

### ISSUE THREAD

**Issue by oroyshocniro** [ZachSaucier/Just-Read#387] opened 2022-03-05 11:03 UTC
… also user selection mode doesn't help, not even in inkognito mode (with Just Read Premium as the only extension permitted to work);

hasn't been working for some weeks now;

thanks for finding/suggesting a fix!

 - macOS (12.2.1)
 - Google Chrome [99.0.4844.51]

**Comment by ZachSaucier** [comment] 2022-03-05 22:07
Hey oroyschocniro. I just tried https://www.autoblog.com/2022/03/01/champion-portable-generator-deal/ and it seemed to work well for me. What sort of error are you having? Just Read not starting?

**Comment by oroyshocniro** [comment] 2022-03-07 19:15
Exactly: simply not starting …
tried with both: extension-button in menu-bar as well as via keyboard
shortcut:
with both the "on"-button appears briefly (3 seconds) but no reader-view
available …

**Comment by Zackuna** [comment] 2022-03-10 17:26
Hi Zach,

I got the same issue as  Oroyshocniro but with a different site, "https://www-tandfonline-com". This is an academic site where I subscribe to Just Read for this page because just read keep the javascript intact. So this is how the problem played out; when I clicked the button, it didn't do anything, but then it just froze the site where I couldn't navigate through it until I restarted the page. I wonder if there is any solution to this. 

![Full article_ ‘The Tyranny of Appearance’_ Chinese Australian Identities and the Politics of Difference - Google Chrome 2022-03-11 01-18-26 (2)](https://user-images.githubusercontent.com/57749628/157720174-56b625cd-0f7d-4375-9b98-ced13f263af7.gif)

Sincerely,
Zac

**Comment by ZachSaucier** [comment] 2022-03-11 02:13
Sorry to hear that you're facing these issues. I am still not having problems with either site that y'all mention. 

Could you please open the developer tools (F12), go to the "Console" tab, try Just Read, and send me a screenshot of any errors that you see?

**Comment by Zackuna** [comment] 2022-03-11 02:41
![Full article_ ‘The Tyranny of Appearance’_ Chinese Australian Identities and the Politics of Difference - Google Chrome 2022-03-11 10-38-15](https://user-images.githubusercontent.com/57749628/157791848-85c4c39e-1b84-405d-b769-63bdfa7cbf62.gif)

Here's another one.

**Comment by ZachSaucier** [comment] 2022-03-11 19:53
Hmm. None of those errors are related to Just Read. 

I'm guessing there's an issue with a conflicting extension. Can you try disabling other extensions, refreshing the page, and trying to use Just Read again?

**Comment by oroyshocniro** [comment] 2022-03-12 16:23
<img width="1829" alt="Bildschirmfoto 2022-03-12 um 17 20 59" src="https://user-images.githubusercontent.com/100998396/158026043-6316b98e-7039-4de5-aa30-9ea40c7577da.png">

Here's a screenshot of the website https://www.autoblog.com/2022/03/01/champion-portable-generator-deal/ next to the console view – thanks for looking into it!

**Comment by ZachSaucier** [comment] 2022-03-12 17:49
Hmm. There is an error that is "coming" from Just Read in that screenshot, @oroyshocniro (`Unexpected token / in JSON...`). But I don't get that error on my devices. And I also don't understand how that error could be reported because the only `JSON.parse` that's in that Just Read script is caught by a `try ... catch`... 

What version of Just Read are you using? You can easily check by right clicking the icon then clicking "Manage extension".

**Comment by oroyshocniro** [comment] 2022-03-13 11:06
it's version 4.2.2 (also updated it, just in case but still the same version no.)

**Comment by ZachSaucier** [comment] 2022-03-15 22:29
Hmm. I'm not sure what could be causing that for you but unfortunately I can't reproduce the issue still so I'm not sure how I can help fix the issue. 

Maybe you could try disabling other extensions and seeing if the issue still occurs? I'm not sure if that could help or not.

**Comment by oroyshocniro** [comment] 2022-03-26 12:25
sorry for the delay!

as mentioned before even in inkognito mode (with Just Read Premium as the only extension permitted to work) it doesn't trigger anything;

in the meantime I found another page that doesn't work with Just Read – it doesn't affect all articles and I haven't found out why this particular one doesn't:
https://www.investing.com/news/stock-market-news/sp-500-in-second-weekly-win-as-dip-buyers-emerge-late-into-close-2792251

But this one does:
https://www.investing.com/news/world-news/as-ukraine-forces-counter-near-kyiv-russia-scales-back-goals-2792326

Interestingly the given webpage by @Zackuna above ( https://www.tandfonline.com/doi/full/10.1080/00233609.2021.1987318 (example article)) does work on my machine.

**Comment by ZachSaucier** [comment] 2022-03-26 14:50
All of those pages work fine for me. Unfortunately without the ability to reproduce I don't think I will be able to help. Closing this issue for now.

**Closed by ZachSaucier** 2022-03-26 14:50 UTC
Labels: bug

**Comment by oroyshocniro** [comment] 2022-10-11 07:03
it's version 4.2.2 (also updated it, just in case but still the same
version no.)
