### ISSUE TITLE
Dashboard: cannot delete entries (Premium feature)

### ISSUE THREAD

**Issue by sophiabrandt** [ZachSaucier/Just-Read#215] opened 2018-11-14 12:46 UTC
version: Just Read: Premium 3.0.13
OS:
* Google Chrome OS Version 70.0.3538.76 (Official Build) (64-bit)
* Manjaro Linux stable channel with Chromium (chromium 70.0.3538.102-1) or Chrome (google-chrome-dev 72.0.3608.4-1)

Problem:
On https://justread.link/dashboard items reappear after I've deleted them.
When I press the "delete" button for an entry, the alert window pops up. When I click ok, the item is removed.
But every time I refresh the dashboard, the entry reappears.
Error happens on both Chromebook (Chrome OS) and Linux desktop machine (Chromium and Chrome).
Also happens in incognito mode with all other extensions disabled.
The developer console doesn't give any errors while deleting, so this doesn't seem to be the issue.
Maybe there is a problem with connecting to the database?

**Comment by ZachSaucier** [comment] 2018-11-14 22:21
Thanks for the report; sorry that this is happening. 

This is definitely something on the server side (AWS). I thought that I set up error catching to not delete entries on the frontend when it's failed to delete the entry on the server side, but it seems like in your case that's not happening. So that must mean that there is some type of successful response, just not the *right* successful response, haha. 

Are you signed into any other Google profiles, or only the one that you bought JRP on?

**Comment by ZachSaucier** [comment] 2018-11-14 23:00
Another thing to try: try clicking on the JR link that the entry that you have deleted shows. If the page does not exist, that means that it successfully deleted from the storage but the database didn't update.

**Comment by sophiabrandt** [comment] 2018-11-15 05:01
@ZachSaucier thanks for the fast reply.
I'm only signed in into the account that I bought JR Premium with.

After I've deleted an entry in the dashboard and the refresh, the JR link still exists.
Example link: [https://justread.link/b_jiDtNFw](https://justread.link/b_jiDtNFw)

So that means it's still in storage?

**Comment by ZachSaucier** [comment] 2018-11-15 14:43
Yes, that means it's failing to delete from the storage and from the DB keeping track of other information. 

What's weird is that I see no errors within the past 4 days in my server logs... So I know it's a sever side issue but no errors are being reported for some reason. I'll continue trying to figure out the issue and report back if I found anything. Thanks for including a problematic URL - that will help me in debugging.

**Comment by ZachSaucier** [comment] 2018-11-15 14:53
I used your user information send a request to delete the entry from my side and it successfully deleted the entry in the DB and from S3... So evidently it's *not* , a server side error like I thought, but instead it's being caused by some failure in the client side (your side) to send a proper `fetch` request... 

Can you try running the following in your console and emailing me the response (**Note** that the response has sensitive information, so please don't post it on this issue)? `chrome.runtime.sendMessage('dpamdgmnffodphoamchpmbclkpmccjga', { getUID: "true" }, function(response) { console.log(response.uid); });`

**Comment by ZachSaucier** [comment] 2018-11-16 18:22
I will continue to look into the real issue and fix it, but we were able to find a temporary solution to deleting entries over email, so if someone reading this has the same issue, please email me at support@justread.link saying so and I can work with you to delete entries.

**Comment by ZachSaucier** [comment] 2018-11-17 14:30
Given I can't reproduce this myself, I can't see anything that could lead to this error in the script, and we found a work around, I'm going to close this issue unless it becomes a problem for other people.

**Closed by ZachSaucier** 2018-11-17 14:30 UTC
Labels: bug
