### ISSUE TITLE
The Notation Feature is Totally Failing!!

### ISSUE THREAD

**Issue by Chuck-7** [ZachSaucier/Just-Read#341] opened 2020-11-28 00:09 UTC
Hi Zach::
Clicking on the Create-Note-Indicator-Circle, causes the Tiny Notation-Box to Instantly Plummet to the VERY Bottom of the Screen.

Thank You,
Chuck Colsch

**Comment by ZachSaucier** [comment] 2020-11-28 00:10
Hey Chuck. Sorry to hear about that issue. I haven't seen that happening. 

Does it happen on every webpage? Or just some?

Are you using Chrome or Edge?

**Comment by Chuck-7** [comment] 2020-11-28 00:17
Actually, it is even WORSE than I thought!!::
When I go to Screen-Bottom, this causes the Note-Box to Totally & Unrecoverably DISAPPEAR!! — After which, the Notation Feature is Non-Functional on that Page.

I’m using Brave.

Thanks, Chuck

**Comment by ZachSaucier** [comment] 2020-11-28 00:23
Hmm. I haven't been able to reproduce the issue yet. 

Can you please share the page that you're trying to add a comment to?

Also are you using a Mac or Windows?

**Comment by Chuck-7** [comment] 2020-11-28 00:27
So Far, it happens on EVERY Page.  I use Brave on Windows.

The Notation Feature is one of the MAIN Features that I use — Although my PREVIOUS usage of Just Read (a couple years ago) was on Chrome.

**Comment by ZachSaucier** [comment] 2020-11-28 00:34
It is working fine for me in Brave on Windows. Maybe your screen size is small? If your screen size is too small the comments get moved to beneath the article. Is that what you're talking about?

**Comment by Chuck-7** [comment] 2020-11-28 00:37
What are you meaning by Screen-Size?  The Monitor? – I have a Full-Size Monitor, and view Brave in Full Screen.

**Comment by ZachSaucier** [comment] 2020-11-28 00:40
Correct, that's what I meant. 

I'm not sure what's going on then. Does the same thing happen if you do the exact same process in Chrome instead?

**Comment by Chuck-7** [comment] 2020-11-28 00:42
Also, I’m not sure if this matters, but my magnification in Windows is 150%.

(I rarely use Chrome And Just Read isn’t installed there.)

**Comment by ZachSaucier** [comment] 2020-11-28 00:43
> my magnification in Windows is 150%

That might be the issue. If there's not enough room for the comments to fit then they go below. If you change your zoom to 100% does the same issue occur?

**Comment by Chuck-7** [comment] 2020-11-28 00:45
Have never attempted it::  I have a large monitor, so at 100% the text is VERY Small.

**Comment by Chuck-7** [comment] 2020-11-28 00:48
I wonder if I can reconfigure my CSS to give it more room??

**Comment by ZachSaucier** [comment] 2020-11-28 00:50
I'd guess so. It's hard to say what you could change it to without seeing it for myself. 

If you're not able to figure it out maybe I could remote in and take a look? If you're open to that you can reach out me at support@justread.link

**Comment by Chuck-7** [comment] 2020-11-28 00:51
Can’t I just paste it onto this Issues Page?

**Comment by ZachSaucier** [comment] 2020-11-28 00:52
Paste what?

**Comment by Chuck-7** [comment] 2020-11-28 00:52
Paste the CSS into this Comment-Screen.

**Comment by ZachSaucier** [comment] 2020-11-28 00:53
The CSS alone isn't enough to figure out what you need. It depends on your screen size and zoom as well.

**Comment by Chuck-7** [comment] 2020-11-28 00:54
But I thought perhaps I could set page-width to Absolute Minimum?

**Comment by ZachSaucier** [comment] 2020-11-28 00:55
I'm not sure what you mean by that.

**Comment by Chuck-7** [comment] 2020-11-28 00:56
The CSS Settings that set any of the Widths.

**Comment by ZachSaucier** [comment] 2020-11-28 00:58
How widths apply depend on the zoom level.

Again, if you can't figure it out I think it'd be easiest if I remote in if and help out.

**Comment by Chuck-7** [comment] 2020-11-28 01:00
Well, the main problem with that is that if my Magnification is Any less than 150%, I cannot see the text properly.

**Comment by ZachSaucier** [comment] 2020-11-28 01:01
I understand. I'm saying I can't really be of help without seeing things for myself 🙂

**Comment by Chuck-7** [comment] 2020-11-28 01:02
What is the process for Remote?

**Comment by ZachSaucier** [comment] 2020-11-28 01:04
We use a software called TeamViewer. You download it, tell me your session code and password (via email), I remote in and try and get it working in the way you need it to work. It's really out of the scope of what I'm responsible for but I'm happy to help if I can.

**Comment by Chuck-7** [comment] 2020-11-28 01:06
Well, what I think would be easier all-round is if you just tell me the, say, 3 KEY Changeable Settings, I will just test those.

**Comment by Chuck-7** [comment] 2020-11-28 01:10
ALSO, might it help if I were to REMOVE Just Read Entirely – – –
And Then RE-Install it?

**Comment by ZachSaucier** [comment] 2020-11-28 01:19
>might it help if I were to REMOVE Just Read Entirely – – –
And Then RE-Install it?

I don't think so.

> you just tell me the, say, 3 KEY Changeable Settings, I will just test those.

I think it is the following:

1. The OS zoom level.
2. The browser zoom level. 
3. The actual Just Read styles. Just Read adds a `.simple-compact-view` class to the body when the window's `innerWidth` minus the `.simple-article-container`'s width is less than 320px (the default width of the comments). That's what pushes the comments down below. You can view the CSS styles for them here: https://github.com/ZachSaucier/Just-Read/blob/master/required-styles.css#L427

To be honest I'm not sure if it's fixable given your zoom level because that calculation is done in the JS. That's why it will take some playing around with values to see.

**Comment by Chuck-7** [comment] 2020-11-28 01:22
SO, The MAXIMAL Possible adjustment to CSS is to do what, please?

**Comment by ZachSaucier** [comment] 2020-11-28 01:25
It depends what you're maximizing. Again, I can't really help without seeing what it's doing myself.

**Comment by Chuck-7** [comment] 2020-11-28 01:26
I want to test ONLY the SINGLE __ULTIMATE__ CSS mod — to eliminate the CSS possibility entirely!!!

**Comment by ZachSaucier** [comment] 2020-11-28 01:28
Hah, you don't really understand what you're saying. There's not one thing to change to make it work.

**Comment by Chuck-7** [comment] 2020-11-28 01:29
But Surely there is a MAXIMUM Reduction of Width!  I only want to Maximal Reduction!!

**Comment by ZachSaucier** [comment] 2020-11-28 01:30
Again, it's unclear what you're suggesting and there likely isn't _one_ property to do what you're wanting. I'm afraid we're going in circles here so I'm going to close this issue.

**Closed by ZachSaucier** 2020-11-28 01:30 UTC
Labels: bug
