### ISSUE TITLE
Just Read for Firefox?

### ISSUE THREAD

**Issue by hiya-tiger** [ZachSaucier/Just-Read#227] opened 2019-01-24 18:41 UTC
Can you bring the extension to Firefox?

**Comment by ZachSaucier** [comment] 2019-01-24 19:51
Hello, 
This is a duplicate of #135. Please keep the discussion to that thread. Thanks!

**Closed by ZachSaucier** 2019-01-24 19:51 UTC
Labels: duplicate

**Comment by ZachSaucier** [comment] 2019-01-24 22:20
What is Waterfox?

**Comment by ZachSaucier** [comment] 2019-05-30 14:02
Apparently there is such thing as [Waterfox](https://www.waterfox.net/). If it's not already supported using the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/just-read-ext/), I likely will not add support because it's not worth the effort. With that being said if someone else wants to do so I am open to pull requests.
