### ISSUE TITLE
"You have too many shared articles - the limit is 100. Please remove some from your user page before adding more."

### ISSUE THREAD

**Issue by amirojkes** [ZachSaucier/Just-Read#199] opened 2018-10-04 15:06 UTC
Hi
I am a premium service customer.
In the past two weeks or so I continue to receive the following message:

"You have too many shared articles - the limit is 100. Please remove some from your user page before adding more."

I do not have any  shared articles in contrast to the post.
Please help
Thanks
Ami

**Comment by ZachSaucier** [comment] 2018-10-04 15:10
Please provide more information. What OS are you on? Can you please provide a screenshot of your page? What does the browser console say?

**Comment by amirojkes** [comment] 2018-10-15 05:16
Win10 home.

**Comment by amirojkes** [comment] 2018-10-15 05:17
![2018-10-15_08-16-53](https://user-images.githubusercontent.com/458718/46931174-b8230a80-d052-11e8-87b5-74bbb02ae79b.png)

**Comment by amirojkes** [comment] 2018-10-15 05:18
chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by amirojkes** [comment] 2018-10-15 05:19
![2018-10-15_08-19-05](https://user-images.githubusercontent.com/458718/46931241-00dac380-d053-11e8-9444-f3afda81e127.png)

**Comment by ZachSaucier** [comment] 2018-10-15 14:04
This looks like the same error as #176. I haven't been able to reproduce it since version 3.0.10.

Does it happen on every web page for you? Or just some?

**Comment by ZachSaucier** [comment] 2018-10-18 12:35
Closing this at least until more information is given.

**Closed by ZachSaucier** 2018-10-18 12:35 UTC
Labels: bug
