### ISSUE TITLE
Only last few paragraphs of article shown.

### ISSUE THREAD

**Issue by icenando** [ZachSaucier/Just-Read#70] opened 2017-04-27 07:55 UTC
The text starts mid-paragraph and only the last paragraphs are shown.

https://www.phaseone.com/Emmanuel-Bournot.aspx?utm_source=newsletter&utm_medium=email&utm_campaign=w17_EmmanuelBournot&pid=&mkt_tok=eyJpIjoiWVRkaU56RTVNalE0TUdNMyIsInQiOiJORWZTZzZZK1dwWWRtTFFsS0pnVzRVM2V4Z3NOMnRsOGRjU3Z0TXFTUndObEUybFBrZ2YwTkl1YlwvanlvZDdNeFVzbnUrOE12Wkp2K0ZzVUEwRW1DRlhwNms3SDh6ZHBJa3FKRmExcEgrOVNicWc1a3ZLR3VCN3pjS1d1N25KYncifQ%3D%3D##ProfileId##

**Comment by ZachSaucier** [comment] 2017-04-27 12:56
Thanks for the report! This is a duplicate of #32, so I'll add it to the running list of sites on that issue and close this issue.

**Closed by ZachSaucier** 2017-04-27 12:56 UTC
Labels: duplicate
