### ISSUE TITLE
Twincities.com

### ISSUE THREAD

**Issue by astrophysically** [ZachSaucier/Just-Read#275] opened 2019-11-06 10:44 UTC
**Describe the bug**
There seems to be a snippet of "evader" code that is corrupting text at twincities.com

**To Reproduce**
1. Go to https://www.twincities.com/2019/11/05/with-trash-in-mind-st-paul-voters-headed-to-the-polls-tuesday/ with ad blocker turned on
2. Click on Just Read
3. Scroll down to the break

**Screenshots**
<img width="616" alt="Screen Shot 2019-11-06 at 5 42 31 AM" src="https://user-images.githubusercontent.com/3966905/68291616-3edcc800-0058-11ea-9ae7-83388b85c022.png">

**Please complete the following information:**
 - OS: MacOS Catlina 10.15
 - Browser: Chrome
 - Version 77.0.3865.120

**Comment by ZachSaucier** [comment] 2019-11-06 13:32
Hello and thanks for the report.

I can't reproduce this on my Mac with Catalina in Chrome. Here's what I see:

![image](https://user-images.githubusercontent.com/3966722/68302315-c1bd4d00-006f-11ea-9975-257a5fdae080.png)

That is indeed some weird behavior, but most likely is unrelated to Just Read. Does the text appear this way for you outside of Just Read? Do you have any non-English language settings enabled on your computer?

**Comment by astrophysically** [comment] 2019-11-06 14:09
Before the splash page comes up, the text reads just fine. It’s only after Just Read is enabled that I get the other result.

**Comment by ZachSaucier** [comment] 2019-11-06 14:13
Splash page? I assume it's some sort of "You've reached your limit of free articles" splash page? Regardless, the content being changed is unrelated to Just Read. You could try [auto-running Just Read](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-auto-run-just-read-on-specific-websites) on this website so that JR may get the content before the splash page comes up. Besides that I can't help you.

I'm closing this issue as it is not a bug with JR.

**Closed by ZachSaucier** 2019-11-06 14:13 UTC
Labels: bug

**Comment by astrophysically** [comment] 2019-11-06 14:23
I think I figured it out, there is a script being run by the source which changes the text upon adblocker detection independent of Just Read. The answer, then, is to disable all adblockers.
