### ISSUE TITLE
"Cannot read property 'indexOf' of undefined" for variable "theme"

### ISSUE THREAD

**Issue by ad101867** [ZachSaucier/Just-Read#10] opened 2016-09-28 00:19 UTC
Hello. LOVE this extension - when it works. Lately it's stopped working. I click on it, and the little red "On" indicator appears - then a couple seconds later, it disappears. And that's it.

Thank you!

**Comment by ZachSaucier** [comment] 2016-09-28 12:01
Hello and thanks for the effort you spent to report the problem! If you can, will you please answer a few questions for me?

- What operating system are you using (Mac, Windows. etc.)?
- What browser are you using (Chrome, Firefox, etc.)?
- What sites have been giving you trouble?

**Comment by ZachSaucier** [comment] 2016-10-03 13:25
I'm closing this issue due to a lack of information to reproduce the errors

**Comment by mxyzplx** [comment] 2016-10-05 19:31
I've had the same problem. 
- Linux (Ubuntu Gnome 16.04)
- Chrome 53.0.2785.143 (64 bit)
- Sites with problems: New York Times, Washington Post

Here's what I've noticed: The Times website rarely works with Just Read, and when it does, the extension only works within a frame, and the surrounding frame structure of the web page remains around the text you want to read. 

It also doesn't seem to make a difference if adblock is turned on or off (I use uBlock Origin).

Something else I've noticed: If I go to a Post page, Just Read will work. If I then go and try a Times page, and Just Read fails, it will then also fail on that same Post page I was just at.

(gifs attached)

![just read_new york times](https://cloud.githubusercontent.com/assets/18336165/19128212/5e402bbc-8b10-11e6-8c6e-59e6d7a21f2e.gif)
![just read_washington post](https://cloud.githubusercontent.com/assets/18336165/19128264/9c99b054-8b10-11e6-87b6-034fdced1f92.gif)

**Comment by mxyzplx** [comment] 2016-10-05 19:44
I've had the same problem. 
- Linux (Ubuntu Gnome 16.04)
- Chrome 53.0.2785.143 (64 bit)
- Sites with problems: New York Times, Washington Post

Here's what I've noticed: The Times website rarely works with Just Read, and when it does, the extension only works within a frame, and the surrounding frame structure of the web page remains around the text you want to read. 

It also doesn't seem to make a difference if adblock is turned on or off (I use uBlock Origin).

Something else I've noticed: If I go to a Post page, Just Read will work. If I then go and try a Times page, and Just Read fails, it will then also fail on that same Post page I was just at.

(gifs attached)

![just read_new york times](https://cloud.githubusercontent.com/assets/18336165/19128212/5e402bbc-8b10-11e6-8c6e-59e6d7a21f2e.gif)
![just read_washington post](https://cloud.githubusercontent.com/assets/18336165/19128264/9c99b054-8b10-11e6-87b6-034fdced1f92.gif)

**Comment by ZachSaucier** [comment] 2016-10-05 20:15
Hey @mxyzplx, thanks for taking the time to add some info. 

I assume the two articles you're trying to read are [this Washington post article](https://www.washingtonpost.com/world/national-security/government-contractor-arrested-for-stealing-top-secret-data/2016/10/05/99eeb62a-8b19-11e6-875e-2c1bfe943b66_story.html) and [this NY Times article](http://www.nytimes.com/2016/10/06/us/nsa-leak-booz-allen-hamilton.html)? Can you please re-test the page using these URLs? Both work for me in Chrome 53 on Windows 10.

If they don't work, could you please include the URLs of the same articles when it doesn't work?

I think may be operating-system-specific as I've had more (inconsistent) trouble with Just Read on my Chromebook than I have on my Windows PC.

**Comment by mxyzplx** [comment] 2016-10-06 04:22
Yep, those are the same links as the articles in the gifs. The Times article (http://www.nytimes.com/2016/10/06/us/nsa-leak-booz-allen-hamilton.html) won't render into Just Read, but the Washington Post article does. 

It doesn't _always_ work like this, but at times when Just Read fails on a Times page, it will then also fail on other pages (like earlier today, it wouldn't render the Washington Post page after it failed on the Times article; however, later it it _did_ render the Washington Post page when I restarted the browser). 

For what it's worth, I tried the same Times article on a Chromebook and had the same result.

**Comment by ZachSaucier** [comment] 2016-10-06 13:18
Thanks for checking. I'm guessing it's OS-specific given ChromeOS is built on Linux. I'll look into it when I get a little time to

**Comment by ZachSaucier** [comment] 2016-10-06 19:06
@mxyzplx Could you check Chrome's console for errors (right click -> inspect element -> go to "Console" panel)? The one I'm getting on the NYTimes article on my chromebook is "Cannot read property 'indexOf' of undefined" that points to a variable called `theme`. Is this the same for you?

I think it may be hardware specific, as the current (bad - left over from when I made this at hackathon last year) way I have this setup is based on time, not a promise or something similar. So I believe on worse devices (or ones that have their processing being taken up elsewhere) it causes the issue at times. 

I'm can fix the issue for me if I increase the timeout, but I'll restructure it to use a promise or something similar as soon as I can

**Comment by ZachSaucier** [comment] 2016-10-06 19:35
I just committed 83ed6ba which I seemingly fixes the issue on my Chromebook by moving some things around (without needing to polyfill promises, whoo!). If you want, you can test it yourself by following the [install instructions for developers](https://github.com/ZachSaucier/Just-Read#install-from-github-for-developers).

I need to do some more testing and fix another issue I came across, but hopefully the fix should be in the store version by Saturday.

**Comment by ad101867** [comment] 2016-10-06 20:01
@ZachSaucier: Thanks for your response to my original post.  In answer to your questions:

•What operating system are you using (Mac, Windows. etc.)?

Windows 7

•What browser are you using (Chrome, Firefox, etc.)?

Chrome

•What sites have been giving you trouble?

Any and all.

**Comment by ZachSaucier** [comment] 2016-10-07 11:44
@ad101867 What type of computer are you on? A high performance one or a cheaper laptop?

**Comment by mxyzplx** [comment] 2016-10-08 22:54
Hey, that 83ed6ba commit worked. I did have the same error in Chrome's console as you had (and a few more, but those were related to a different extension). So the error you were seeing on a Chromebook is the same one occurring in Linux. 

If you need any more testing done, I'll see what I can do.

**Comment by ZachSaucier** [comment] 2016-10-09 14:09
This fix should be live in version 1.0.5 which is uploaded now. 

@ad101867 Please try the sites that gave you issue using version 1.0.5 to see if the problems have been resolved

**Comment by mxyzplx** [comment] 2016-10-09 17:17
I've tried the new version, 1.05, and things are looking pretty good. 

One question -- and I'll open a new bug for this if need be -- if you go to thehill.com (a Washignton D.C. politics website), every link in the body of the text has its metadata rendered as text when opened in Just Read. 

Take any article on thehill.com, and mouse over any link in the text -- a pop-up pops up, often with a photo and with links to other stories related to that link. Once rendered in Just Read, all of that info -- the photo and the links -- will appear in the middle of the text right after the initial linked text, often adding multiple lines of needless text in the middle of a paragraph.

To be fair, this is also a problem with Readable and Clearly, so it's not just a Just Note thing. Just something I thought could be brought up.

**Comment by ZachSaucier** [comment] 2016-10-09 17:25
@mxyzplx That's not a problem that Just Read could generically handle. 

However, you can edit your version (right click the Just Read extension -> click Options -> edit the CSS) by pasting in the following:

```
 .rollover-people-block {
    display: none;
}
```

And save it, making sure the new stylesheet is the "used" one, and they won't show up for you. I won't add this to the generic stylesheet because it's too site specific.

**Comment by mxyzplx** [comment] 2016-10-09 17:28
Oh, that was too easy. I'll keep that in the stylesheet, but would it cause problems on other sites? If so, I'll just deal with The Hill's oddity.

**Comment by ZachSaucier** [comment] 2016-10-09 17:31
@mxyzplx If you change it in your Just Read stylesheet, it won't affect any regular pages at all. It will only change the way Just Read renders the content. However, since there is no site-specific stylesheet for Just Read at the moment (I've thought about trying to include it, but at the moment it seems like too much work to be worth the value), it would affect any other sites that have content that Just Read includes with the class `rollover-people-block` (which is few and far between because it's not a common class name).

**Comment by mxyzplx** [comment] 2016-10-09 17:34
Got it. Think I'm all set then. And thanks again for this extension. Ever Clearly dove, I was looking for something that just helped reading and didn't force you to store pages in the cloud or anything -- something simple. I know my dad is looking for something similar, and I'll pass this along.

**Comment by ad101867** [comment] 2016-10-11 23:05
@ZachSaucier: I'm using an Acer Aspire X3910.  Okay, I've just installed JR version 1.05.  Previously NO websites worked with JR, but now I find a new problem.  _Some_ sites will work fine, but others will show the JR popup window with _no content except the title of whatever the page is_.

Also, am I mistaken in thinking that the older version included the URL and date visited?  If that's the case, 1.05 doesn't do that.  And should I be able to delete images?

Thanks for your help.

**Comment by ZachSaucier** [comment] 2016-10-12 12:42
@ad101867 I'm glad to hear that there's been improvement! Could you please link any sites that don't work for you, that loading the title as you say? As for this page, it's not an article type of page that Just Read was meant to be used on. Please make sure that the page you're testing is an article-based page.

No version of Just Read has included the URL or date visited.

**Comment by ZachSaucier** [comment] 2016-10-27 17:56
I'm closing this issue to solving one issue and getting a lack of response in regards to the other

**Closed by ZachSaucier** 2016-10-27 17:56 UTC
Labels: bug
