### ISSUE TITLE
unable to read this article

### ISSUE THREAD

**Issue by suredream** [ZachSaucier/Just-Read#85] opened 2017-07-15 17:29 UTC
[This artible](http://lithub.com/why-you-should-aim-for-100-rejections-a-year/?utm_source=wanqu.co&utm_campaign=Wanqu+Daily&utm_medium=website)

**Comment by ZachSaucier** [comment] 2017-07-15 17:32
Thanks for the report! 

This is a duplicate of #32, so I'll close this issue as a duplicate and add this site to the running list of problematic sites there. As it says in that issue, you can use user selection mode for now until this gets fixed.

**Closed by ZachSaucier** 2017-07-15 17:32 UTC
Labels: duplicate
