### ISSUE TITLE
Start reading at scroll position

### ISSUE THREAD

**Issue by X-F0RCE** [ZachSaucier/Just-Read#241] opened 2019-03-20 23:02 UTC
is this possible?

**Comment by ZachSaucier** [comment] 2019-03-20 23:13
Yes, this is possible using Just Read's text selection functionality. At the scroll position (or wherever you want to start), just highlight the text and then scroll to the bottom of the article. Then right click the highlighted selection and click "View this selection in Just Read".

**Comment by X-F0RCE** [comment] 2019-03-20 23:15
Thanks for the quick reply, Zach 😄

I use ALT+Z to initiate Just Read and wondered if it can be applied to this workflow?

Say I'm scrolling down an article, a certain point I hit my hotkey, and boom Just Read does its magic and renders but scrolled down at that point maybe?

**Comment by ZachSaucier** [comment] 2019-03-20 23:18
It's possible for Just Read to be modified to behave in such a way as you describe but I can't see it being used often. Most the time users see ugly pages and immediately start Just Read, not wait until they've read most of the article to initiate it.

**Comment by X-F0RCE** [comment] 2019-03-20 23:19
True! I must admit I have only been doing this where I'm currently theming and constantly reloading the plugin.

**Comment by ZachSaucier** [comment] 2019-03-20 23:23
If your test page has ID selectors in it, you can start Just Read at a given ID location. For example if you start Just Read on https://css-tricks.com/minecraft-webvr-html-using-frame/#toc-snapcomponent it will start at the "Snap component" section (but then images and such will load and it will be further down in the page). Then you could use your keyboard shortcuts to start and exit Just Read to that location.

**Comment by X-F0RCE** [comment] 2019-03-20 23:25
Interestingly, mine doesn't snap to anchors/ID #s

**Comment by ZachSaucier** [comment] 2019-03-20 23:26
What version and OS are you on?

**Comment by ZachSaucier** [comment] 2019-03-20 23:27
And you tried clicking the link in the post above and starting JR after the page has loaded?

**Comment by X-F0RCE** [comment] 2019-03-20 23:29
JR: 1.6
OS: Win10 Version	10.0.17134 Build 17134

Maybe it's my theme? 😅

**Comment by ZachSaucier** [comment] 2019-03-20 23:30
I'm on the same version and OS. It couldn't be your theme. I think it has to be user error 😛

**Comment by X-F0RCE** [comment] 2019-03-20 23:41
Your plugin has got me back into coding and tinkering through this css/html and by the looks of it js. here's a video/GIF - I swear it's not user error 😅
![jr-noanchor](https://user-images.githubusercontent.com/25463614/54726139-9e3da480-4b69-11e9-9f39-650a04a76501.gif)

**Comment by ZachSaucier** [comment] 2019-03-20 23:46
Ya, interesting. I was mostly kidding about the user error. I don't know why it doesn't jump there as [it's supposed to](https://github.com/ZachSaucier/Just-Read/blob/4edf9e564d153314b3703ff05f626782cf35a978/content_script.js#L1382). Maybe it's a race condition of some sort, like your browser is calling that line before JR loads fully. You could test that by using your dev tools to change `simpleArticleIframe.location.hash = top.window.location.hash;` to `setTimeout(function () { simpleArticleIframe.location.hash = top.window.location.hash; }, 10);` if you wanted to.

**Comment by X-F0RCE** [comment] 2019-03-20 23:51
Oh I know, its all cool dude.

Could it be recent Chrome 73.0.3683.86, or a conflicting extension?

**Comment by ZachSaucier** [comment] 2019-03-20 23:53
I suppose it could be a conflict with another extension though I wouldn't know why that would be the case. I'd put my money on it being an environmental/PC-specific issue in regards to the order in which things are loaded when. I can test on my wife's (nicer) laptop and let you know if I can reproduce that behavior.

**Comment by X-F0RCE** [comment] 2019-03-21 00:04
Please don't have it as a priority, I don't want to be sapping your precious time. 

How is it that I alter the extension? Is it Developer Mode > Load Unpacked?

**Comment by ZachSaucier** [comment] 2019-03-21 00:13
To run it from a local copy you need to [download it as a ZIP](https://github.com/ZachSaucier/Just-Read/archive/master.zip) and then go to [chrome://extensions/](chrome://extensions/) and click "Load Unpacked", yes. That will allow you to make any changes you want to JR (most of JR is in the content_script.js file).

**Comment by X-F0RCE** [comment] 2019-03-21 00:14
Thank you very much for the discussion and help, Zach!

**Comment by ZachSaucier** [comment] 2019-03-21 00:19
I'm happy to help.

I tried testing this functionality on my wife's computer and was unable to reproduce the behavior you show in the screen capture. If you can figure it out then let me know, but as it is I think it's unlikely that i can figure it out remotely like this (and it's not a big deal anyway).

**Comment by X-F0RCE** [comment] 2019-03-21 00:36
Okay, so I just re-added the extension and using the default theme and either the button, the default hotkey CTRL+SHFT+L, or my own ALT+Z, the anchor is overshot. Using my own theme, it doesn't work at all. In the unpacked version I get the same result, and I just figured out why...I was hiding all headers 😅🔫

**Comment by ZachSaucier** [comment] 2019-03-21 00:43
Ah, I guess that makes sense. I thought Chrome would jump to IDs even if the element was hidden, but I guess not.

The overshooting is coming from the images/examples being loaded as [I mentioned above] (https://github.com/ZachSaucier/Just-Read/issues/241#issuecomment-475066230).

Closing this issue then.

**Closed by ZachSaucier** 2019-03-21 00:43 UTC
Labels: enhancement, question

**Comment by ZachSaucier** [comment] 2019-03-21 14:03
Whenever you get done with your theme you should [share it](https://github.com/ZachSaucier/Just-Read/issues/4)!
