### ISSUE TITLE
Just-Read does not work correctly for The Daily Mail's website

### ISSUE THREAD

**Issue by ThurstonBT** [ZachSaucier/Just-Read#384] opened 2022-01-26 01:35 UTC
Just-Read does not work correctly for The Daily Mail's website; and if there ever was a website the reading of which would benefit more from Just-Read's reformatting services, I can't cite one.

This is an example of a Daily Mail article for which Just-Read fails to display the article's text —
https://www.dailymail.co.uk/news/article-10440555/U-S-Labor-Dept-withdrawing-COVID-vaccine-rule-large-employers.html

**Describe the bug**
Just-Read fails to display the article text for pages at https://www.dailymail.co.uk

**To Reproduce**
1. Go to https://www.dailymail.co.uk/news/article-10440555/U-S-Labor-Dept-withdrawing-COVID-vaccine-rule-large-employers.html
2. Click on the Just-Read browser icon.
3. The article text is not displayed but other blather is.

**Expected behavior**
I expected that the article text would be displayed.

**Please complete the following information:**
 - OS: Windows 7
 - Browser Chrome
 - Version Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by ZachSaucier** [comment] 2022-01-29 14:50
Hey Thurston, thanks for posting. 

This is a duplicate of #244. I recommend using Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to get around this issue. Besides that, I'm very open to suggestions about how to [improve Just Read's selection algorithm](https://github.com/ZachSaucier/Just-Read/issues/331)!

**Closed by ZachSaucier** 2022-01-29 14:50 UTC
Labels: bug
