### ISSUE TITLE
Partial display

### ISSUE THREAD

**Issue by AnjnShan** [ZachSaucier/Just-Read#438] opened 2024-05-24 03:24 UTC
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
>It does not fully display text on certain pages.

**To Reproduce**
1. Go to 'https://www.starwars.com/databank/jedi-temple'
2. Click on 'Just Read'
3. Scroll down to 'Literally anything'

**Expected behavior**
The page would display more than the first paragraph, only.

**Screenshots**
N/A

**Please complete the following information:**
- Avast Secure Browser

**Additional context**

**Comment by ZachSaucier** [comment] 2024-05-24 04:41
Hey Anjn, thanks for posting.

The page that you linked is more of a wiki than a web article. As such, it is outside of the focus of Just Read. I'm not surprised that the auto-selection doesn't work as you expect. As such, I'm closing this as "by design".

You can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read?tab=readme-ov-file#user-selection-mode) in cases like this to manually select the content that you want to read. If you use this site regularly, Just Read Premium has [extra functionality](https://github.com/ZachSaucier/Just-Read?tab=readme-ov-file#user-content-selectors) which lets you customize what Just Read selects on particular domains.

**Closed by ZachSaucier** 2024-05-24 04:41 UTC
Labels: bug
