### ISSUE TITLE
Can't use the brush icon

### ISSUE THREAD

**Issue by excelsse** [ZachSaucier/Just-Read#139] opened 2018-02-26 19:44 UTC
Supposedly I could change the parameters of how the web is displayed. But the brush icon doesn't work, at all. It doesn't open any window, it simply does nothing.

**Comment by ZachSaucier** [comment] 2018-02-27 17:50
This seems to be a duplicate of #136. Are you on Linux?

**Comment by ZachSaucier** [comment] 2018-03-02 03:18
Due to the lack of response, I'm going to assume that this is a duplicate.

**Closed by ZachSaucier** 2018-03-02 03:18 UTC
Labels: duplicate
