### ISSUE TITLE
Just-read stops rendering at encountered blockquote

### ISSUE THREAD

**Issue by jbfriedrich** [ZachSaucier/Just-Read#171] opened 2018-07-30 11:58 UTC
I just tried the extensions for the first time and most of the time it works great. But whenever a blockquote on the Spiegel Plus category on the German Spiegel website occurs, it stops rendering as if the page was finished. I hope the screenshots make it clear:

![screen shot 2018-07-30 at 13 52 46](https://user-images.githubusercontent.com/1968991/43395986-5f202ab4-9400-11e8-9dfe-e5fba0bfa5b6.png)

![screen shot 2018-07-30 at 13 52 58](https://user-images.githubusercontent.com/1968991/43395997-68fb0dc4-9400-11e8-88ed-eaab433594ae.png)

![screen shot 2018-07-30 at 13 52 23](https://user-images.githubusercontent.com/1968991/43396009-734fa91a-9400-11e8-9330-29a6b918c0a6.png)

I didnt see any obvious way in the theme to change it, maybe it can be fixed very easily and I just dont know how. [This is the page](http://www.spiegel.de/plus/horst-seehofer-minister-mit-begrenzter-laufzeit-a-00000000-0002-0001-0000-000158616265) in questions (but I think the full page is hidden behind the paywall).

Please let me know how I can help. Thanks!

**Comment by ZachSaucier** [comment] 2018-07-30 12:59
Thanks for the report!

This seems to be the same issue as #95 but I can't make sure because the article you link to is behind a paywall. Can you please confirm that this is the case?

As is the case with #95, you can likely work around the failure of JR's auto-selection by using [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode).

**Comment by jbfriedrich** [comment] 2018-07-31 12:52
Hey @ZachSaucier, thanks for the quick reply. I tried the auto-selection, but that did only work okay-ish. It selected a lot of pictures and stuff that I did not want and seemed a bit flimsy when you had to select a lot of text (as its a huge page).

Would it help if I could provide a copy of the article (i.e. save the HTML page)?

**Comment by ZachSaucier** [comment] 2018-07-31 12:54
Ya, that should be fine.

**Comment by jbfriedrich** [comment] 2018-07-31 16:16
Please see attached [ZIP archive](https://github.com/ZachSaucier/Just-Read/files/2246155/Archive.zip). I would think its the weird way they structure their article. Hope that helps. 

Thanks for your quick reply. Much appreciated. Once you've got a premium version ready, I'll give it a try!

**Comment by ZachSaucier** [comment] 2018-07-31 19:25
Yep, it's a dupe of #95. I'm going to close this issue as a duplicate of it and add this URL to the list of problematic domains on that issue. 

Thanks again for the report!

**Closed by ZachSaucier** 2018-07-31 19:25 UTC
Labels: duplicate
