### ISSUE TITLE
Not working on the site below

### ISSUE THREAD

**Issue by raphaelfsalomao** [ZachSaucier/Just-Read#76] opened 2017-06-07 17:57 UTC
http://g1.globo.com/politica/noticia/em-cerimonia-no-planalto-temer-diz-que-conduzira-governo-ate-31-de-dezembro-de-2018.ghtml

**Comment by ZachSaucier** [comment] 2017-06-07 18:00
Thanks for the report!

This is a dupe of #32. You can find a work around there using user selection mode. I'll add this site to the running list there.

**Closed by ZachSaucier** 2017-06-07 18:00 UTC
Labels: duplicate
