### ISSUE TITLE
Website overrides new design to provide error message

### ISSUE THREAD

**Issue by Along222** [ZachSaucier/Just-Read#71] opened 2017-05-16 06:58 UTC
https://www.epo.org/law-practice/legal-texts/html/guidelines/e/f_vi_1_5.htm

Instead of desired article, website shows:

New look and feel for EPO website

 X 
We have redesigned the EPO website to give it a new look and feel. To ensure that the new layout is displayed correctly by your browser(s), we recommend you clear your browser cache.

� How to refresh your browser's cache

**Comment by ZachSaucier** [comment] 2017-05-17 03:19
Thanks for the report! This is a duplicate of #67. I'm closing it as such and will add it to a running list of sites that share the same issue.

**Closed by ZachSaucier** 2017-05-17 03:19 UTC
