### ISSUE TITLE
Issues with reading email in Gmail

### ISSUE THREAD

**Issue by orschiro** [ZachSaucier/Just-Read#16] opened 2016-10-17 06:49 UTC
Hi @ZachSaucier,

I have a problem reading an email in Gmail. 

Since it contains private information, I am forwarding you this email directly. 

I hope that's fine with you.

Thanks,

-Robert

**Comment by ZachSaucier** [comment] 2016-10-17 12:32
Thanks for bringing this up. There was an error caused by the quotes because I was failing to escape them properly. Now that is fixed, but I realize that the way Chrome builds their selection function is that it returns only text, not any DOM, which leaves the selected content pretty ugly. 

So, I switched up how it works so that the DOM is selected instead of just the text. It should be fixed in the next version (I'll push the changes now).

**Closed by ZachSaucier** 2016-10-17 12:32 UTC

**Comment by orschiro** [comment] 2016-10-17 12:58
Wow, thanks so much for having found a fix so quickly!

**Comment by ZachSaucier** [comment] 2016-10-17 13:33
After I uploaded the change listed above in version 1.0.6 I realized in the shower that I didn't implement it correctly. I've now fixed the bug, so version 1.0.7 should work correctly
