### ISSUE TITLE
Too many shared articles also....

### ISSUE THREAD

**Issue by rhtCanuck** [ZachSaucier/Just-Read#240] opened 2019-03-19 19:24 UTC
Hi Zach. I just got the too many shared error as well, even though i have only 2 listed as being shared. I restarted my browser and it hasn't re-occurred, so i'm including this just for more information for you...

I'm using JustRead premium 3.4.0
Windows 10 Pro, v 1809
Google Version 75.0.3738.0 (Official Build) canary (64-bit) ( i know, its unsupported, but i only got the error once so i can't reproduce it anywhere)

Observations:
- i have seen that error occur a few times, temporarily. if you're watching close, it appears, then goes away quickly and then it continues ok. 
- I do a lot of copy/paste of the just-readed(not sure of the proper verb form here) page into another reading app. its entirely possible that i've done more than 100 cut/pastes since the browser was bounced.. i'll try and keep better track to see if that happens again at about 100 times.....
Hope this helps
Randy

**Comment by rhtCanuck** [comment] 2019-03-19 19:33
would turning on chrome logging pick up anything if it occurs again?

**Comment by ZachSaucier** [comment] 2019-03-19 21:02
If it is occurring and then going away quickly it probably means that the stylesheet is just slow in loading.

I'm not sure exactly what you mean by "Chrome logging" but if it is recording all things that go inside of Chrome's console it'd probably show you a related error if it happens.

**Comment by ZachSaucier** [comment] 2019-03-24 14:16
I'm going to close this as there's not really anything to be done. Please let me know if you can reproduce the error consistently!

**Closed by ZachSaucier** 2019-03-24 14:16 UTC

**Comment by ZachSaucier** [comment] 2019-04-05 20:51
[As mentioned](https://github.com/ZachSaucier/Just-Read/issues/218#issuecomment-480417738) in the primary issue, this is likely due to a user not enabling Chrome's syncing on their account. To have sharing work, please enable that setting as the linked comment says.
