### ISSUE TITLE
option to change image size in GUI

### ISSUE THREAD

**Issue by WimDeBacker** [ZachSaucier/Just-Read#202] opened 2018-10-05 09:30 UTC
I'm sorry for the many submissions but I'm currently playing with Just Read and all these issues seem important to me.

enhancement:
I think an option to change the image size should also be a setting in the GUI. The size of images is an important  part page.

Thanks 
Wim

> Thanks for wanting to help improve Just Read! 
> 
> Looking through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) may help you with your request. Please look through [the existing posts](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment] 2018-10-05 12:34
Thanks for the suggestion. 

The current default functionality is to limit the image to the width of images to the content's width. When would you want something other than that? I can't think of any good use cases for having more easy control over image sizing.

**Comment by ZachSaucier** [comment] 2018-10-18 12:34
Closing this at least until more information is given.

**Closed by ZachSaucier** 2018-10-18 12:34 UTC
Labels: enhancement

**Comment by jerryasher** [comment] 2019-03-04 02:43
Well, it seems that every single recipe website has gone to making their content have huge, absolutely huge images, to encourage readers to scroll through, see ads I guess. Often there is very little content apart from the images and the recipe directions themselves are buried at the bottom.

This page is an example:
https://minimalistbaker.com/how-to-make-cauliflower-rice/

It has five images that are 1456x2126 (or greater).  On most people's 1080p displays, that's almost two pages of scrolling for each image!

Even when reduced to a column width of 600, that's a vertical size of 876, which is still an image that is 80% of the page size on desktop, for images that provide little.

So it would be very helpful if I could have setting or buttons that allow for resizing all images to less than column width x column width, or 500 x 500, or whatever. Or perhaps a button allowing me to instantly resize images, or a resize drag thingy on each image. Or just delete images. Or present thumbnails for each image.

And there is nothing special about the website I linked to.  Many many websites are doing these things.

**Comment by ZachSaucier** [comment] 2019-03-04 13:28
@jerryasher Thanks for looking through the old issues before posting! 

I still don't think this feature warrants a part of the GUI. You can change the image size (or hide them completely) in CSS by adding something like `image { max-width: 20%; }`. You could even have an exact duplicate of the theme you normally use with this one change and go between them using the GUI's theme selection functionality. 

Side note: Just Read Premium does have an image lightbox functionality built in, which would make themes that resize images to thumbnails more useful.
