### ISSUE TITLE
Comment selected instead of content

### ISSUE THREAD

**Issue by multlurk** [ZachSaucier/Just-Read#133] opened 2018-01-20 10:05 UTC
No content. There is only a heading. https://habrahabr.ru/company/piter/blog/346358/

![screenshot 2018-01-20 13 07 13](https://user-images.githubusercontent.com/12564221/35182301-dc8a57e0-fde2-11e7-83c0-b77843b581bd.png)
![screenshot 2018-01-20 13 07 03](https://user-images.githubusercontent.com/12564221/35182302-dca7bdee-fde2-11e7-8f29-e00d8c0f6039.png)

**Comment by ZachSaucier** [comment] 2018-01-20 14:01
Thanks for the report! Just Read is erroneously selecting the comments section, which it's not supposed to do, and then hides the selected comments, which it is supposed to do. I'll see if I can improve Just Read's auto-selection to not select comments in cases like this one. Until that happens, you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the correct content on problematic pages like this.

**Comment by ZachSaucier** [comment] 2018-01-20 14:03
The root cause is the same as in another issue, #94, so I'll add this problematic site to the list of sites on that issue and close this issue.

**Closed by ZachSaucier** 2018-01-20 14:03 UTC
Labels: bug
