### ISSUE TITLE
Google Dictionary Double Click for Definition Feature not Working

### ISSUE THREAD

**Issue by jimnrd** [ZachSaucier/Just-Read#221] opened 2018-12-19 12:05 UTC
Hi there,

I use the Google Dictionary Chrome extension all the time to define words.
The app seems to work in other apps on Chrome, however not with Just Read.

It would be great if this was working so you can double click on a word when in read view to get the definition for a word.

Many thanks and Merry Christmas!

James

**Comment by ZachSaucier** [comment] 2018-12-19 13:00
Hey James. Merry Christmas and thanks for posting! 

This is actually a duplicate of #29. This is technically an issue with the Google Dictionary extension. So it'd be better to reach out to them about it.

You can work around the issue by using shared pages (available in Just Read Premium) but there's not anything I can do about it without changing a large part of how Just Read works which is unlikely to happen.

Sorry if that's not the information you're looking to hear!

**Closed** 2018-12-19 13:13 UTC
Labels: duplicate
