### ISSUE TITLE
500 error clicking Share button

### ISSUE THREAD

**Issue by fredmeews** [ZachSaucier/Just-Read#185] opened 2018-08-15 14:01 UTC
Original page: https://hackernoon.com/40-ways-to-invest-in-more-resilient-teams-c2ac7d008591
Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
MacOS: 10.13.6 (17G65)
JR Version: Premium 3.0.6

After making a few deletions, highlights & comments... clicked the Share button.  No link appeared and noted the following on JS console.

```
content_script.js:1765
POST https://justread.link/newEntry 500 (Internal Server Error)
(anonymous)	@	content_script.js:1765
sendResponseAndClearCallback	@	VM224 extensions::messaging:419
messageListener	@	VM224 extensions::messaging:451
EventImpl.dispatchToListener	@	VM217 extensions::event_bindings:403
publicClassPrototype.(anonymous function)	@	VM223 extensions::utils:138
EventImpl.dispatch_	@	VM217 extensions::event_bindings:387
EventImpl.dispatch	@	VM217 extensions::event_bindings:409
publicClassPrototype.(anonymous function)	@	VM223 extensions::utils:138
dispatchOnMessage	@	VM224 extensions::messaging:392


content_script.js:1813
Fetch Error =
Response {type: "cors", url: "https://justread.link/newEntry", redirected: false, status: 500, ok: false, …}
body
:
(...)
bodyUsed
:
false
headers
:
Headers {}
ok
:
false
redirected
:
false
status
:
500
statusText
:
"Internal Server Error"
type
:
"cors"
url
:
"https://justread.link/newEntry"
__proto__
:
Response
(anonymous)	@	content_script.js:1813
Promise.catch (async)		
(anonymous)	@	content_script.js:1804
sendResponseAndClearCallback	@	VM224 extensions::messaging:419
messageListener	@	VM224 extensions::messaging:451
EventImpl.dispatchToListener	@	VM217 extensions::event_bindings:403
publicClassPrototype.(anonymous function)	@	VM223 extensions::utils:138
EventImpl.dispatch_	@	VM217 extensions::event_bindings:387
EventImpl.dispatch	@	VM217 extensions::event_bindings:409
publicClassPrototype.(anonymous function)	@	VM223 extensions::utils:138
dispatchOnMessage	@	VM224 extensions::messaging:392
```

**Comment by ZachSaucier** [comment] 2018-08-15 14:17
Sorry this is happening for you, but thanks for the report. I can't reproduce it on my end given the information. 

What version of Just Read Premium are you currently using? The latest version should be 3.0.6. You can check by right clicking JRP and selecting "Manage extensions".

If you start JRP and then try to share the page immediately after you start it (without making highlights, comments, or deletions), does it still give you the same error?

**Comment by fredmeews** [comment] 2018-08-15 14:30
Wow - fast response, thank you!  

Yes it's 3.0.6 premium.   It does not happen if I share immediately after starting.  Let me know what else might help to debug.
 -Ed

**Comment by ZachSaucier** [comment] 2018-08-15 16:11
You can try to do the same actions that you did before, sharing intermittently to make sure that it's working correctly. By this I mean make some changes (highlighting, commenting, deleting, etc.), share -> make sure it works, then repeat until it stops working. If it breaks then share here what broke it. Maybe try just doing that one action after restarting JRP to see if it alone breaks the sharing feature. 

At the end of this process you might want to remove the shared versions you created to test using https://justread.link/dashboard so you don't have them contributing towards your max number of shared articles (100 is the current cap).

**Comment by fredmeews** [comment] 2018-08-15 16:53
Sure, but since it generated a 500 error... is that something you can check in the server logs on your side?

**Comment by ZachSaucier** [comment] 2018-08-15 17:00
Ya, I see some errors in the logs. They're pretty general saying the input is invalid. The error is almost certainly on the extension's submission side (a bug in JRP's code).

**Comment by ZachSaucier** [comment] 2018-08-19 21:33
Any update about this?

**Comment by ZachSaucier** [comment] 2018-08-23 13:43
Closing this until more feedback is provided on how to reproduce it.

**Closed by ZachSaucier** 2018-08-23 13:43 UTC
Labels: bug
